#!/usr/bin/env python3
"""Visible order-4 eigenspace screen for the p27 E' quotient lane.

The T-cover twist obstruction identifies the concrete eigenspace object

    j^2 = -1,  Z = T*(1 - j/X^3),  sigma(Z) = j*Z.

This probe asks the next bounded question: do d3 or d4 become visible as a
quadratic character over F_{q^2} of the first named eigenspace packets
generated by Z, Z^2, Z^4 and the existing E' branch factors?

It is deliberately a falsifier for a natural Hilbert-90 packet, not a broad
arbitrary coefficient fit.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import dataclass
from typing import Callable

from p27_reverse_doubling_source_probe import enumerate_small_prime_candidates
from p27_reverse_source_d4_recurrence_probe import candidate_bits


@dataclass(frozen=True)
class Fq2:
    a: int
    b: int
    q: int

    def __post_init__(self) -> None:
        object.__setattr__(self, "a", self.a % self.q)
        object.__setattr__(self, "b", self.b % self.q)

    def __add__(self, other: "Fq2") -> "Fq2":
        self._check(other)
        return Fq2(self.a + other.a, self.b + other.b, self.q)

    def __sub__(self, other: "Fq2") -> "Fq2":
        self._check(other)
        return Fq2(self.a - other.a, self.b - other.b, self.q)

    def __neg__(self) -> "Fq2":
        return Fq2(-self.a, -self.b, self.q)

    def __mul__(self, other: "Fq2") -> "Fq2":
        self._check(other)
        return Fq2(
            self.a * other.a - self.b * other.b,
            self.a * other.b + self.b * other.a,
            self.q,
        )

    def _check(self, other: "Fq2") -> None:
        if self.q != other.q:
            raise ValueError("mixed fields")

    def is_zero(self) -> bool:
        return self.a % self.q == 0 and self.b % self.q == 0

    def conj(self) -> "Fq2":
        return Fq2(self.a, -self.b, self.q)

    def norm(self) -> int:
        return (self.a * self.a + self.b * self.b) % self.q


def fq2(q: int, a: int, b: int = 0) -> Fq2:
    return Fq2(a, b, q)


def fq2_pow(value: Fq2, exponent: int) -> Fq2:
    out = fq2(value.q, 1)
    base = value
    exp = exponent
    while exp:
        if exp & 1:
            out = out * base
        base = base * base
        exp >>= 1
    return out


def fq2_chi(value: Fq2) -> int:
    if value.is_zero():
        return 0
    r = fq2_pow(value, (value.q * value.q - 1) // 2)
    if r == fq2(value.q, 1):
        return 1
    if r == fq2(value.q, -1):
        return -1
    raise ValueError(f"unexpected quadratic character result {r}")


def legendre(a: int, q: int) -> int:
    a %= q
    if a == 0:
        return 0
    r = pow(a, (q - 1) // 2, q)
    return 1 if r == 1 else -1


def inv(a: int, q: int) -> int:
    return pow(a % q, q - 2, q)


@dataclass(frozen=True)
class EigenspaceRow:
    x: int
    w: int
    t: int
    u: int
    v: int
    z: Fq2
    d3: int
    d4: int | None


def base_features(u: int, v: int, q: int) -> list[tuple[str, int]]:
    features: list[tuple[str, int]] = [
        ("1", 1),
        ("U", u),
        ("V", v),
        ("U2+4", u * u + 4),
        ("U2-4", u * u - 4),
        ("U2+1", u * u + 1),
        ("U2-1", u * u - 1),
        ("U2+2U+4", u * u + 2 * u + 4),
        ("U2-2U+4", u * u - 2 * u + 4),
    ]
    for c in (-4, -2, -1, 1, 2, 4):
        features.append((f"U{c:+d}", u + c))
    for a in (-4, -2, -1, 1, 2, 4):
        features.append((f"V{a:+d}U", v + a * u))
    return [(name, value % q) for name, value in features]


def eigenspace_packets(row: EigenspaceRow) -> list[tuple[str, Fq2]]:
    q = row.z.q
    one = fq2(q, 1)
    z = row.z
    z2 = z * z
    z4 = z2 * z2
    packets: list[tuple[str, Fq2]] = [
        ("Z", z),
        ("Z2", z2),
        ("Z4", z4),
        ("Z+1", z + one),
        ("Z-1", z - one),
        ("Z2+1", z2 + one),
        ("Z2-1", z2 - one),
        ("Z4+1", z4 + one),
        ("Z4-1", z4 - one),
    ]
    for name, value in base_features(row.u, row.v, q):
        base = fq2(q, value)
        packets.extend(
            [
                (f"Z+{name}", z + base),
                (f"Z-{name}", z - base),
                (f"Z2+{name}", z2 + base),
                (f"Z2-{name}", z2 - base),
                (f"Z4+{name}", z4 + base),
                (f"Z4-{name}", z4 - base),
                (f"Z*{name}", z * base),
            ]
        )
    # Component characters of the invariant Z^4.  These are still named by the
    # eigenspace construction, but evaluated back in the base field.
    packets.extend(
        [
            ("base_ReZ4", fq2(q, z4.a)),
            ("base_ImZ4", fq2(q, z4.b)),
            ("base_ReZ4+ImZ4", fq2(q, z4.a + z4.b)),
            ("base_ReZ4-ImZ4", fq2(q, z4.a - z4.b)),
        ]
    )
    return packets


def collect_rows(q: int) -> tuple[list[EigenspaceRow], Counter[str]]:
    candidates, enum_stats = enumerate_small_prime_candidates(q)
    stats: Counter[str] = Counter({f"enum_{key}": value for key, value in enum_stats.items()})
    rows: list[EigenspaceRow] = []
    seen: set[tuple[int, int, int, int, int, int]] = set()
    for cand in candidates:
        bits = candidate_bits(cand, q)
        if bits.d3 not in (-1, 1):
            stats["d3_unusable"] += 1
            continue
        x = int(cand["X"]) % q
        if x == 0:
            stats["x_zero_skip"] += 1
            continue
        w = int(cand["W"]) % q
        t = int(cand["T"]) % q
        x2 = x * x % q
        u = (x - inv(x, q)) % q
        v = w * (x2 + 1) % q * inv(x2, q) % q
        if (v * v - (u * u % q * u + 4 * u)) % q != 0:
            stats["Eprime_mismatch"] += 1
            continue
        z = fq2(q, t, -t * inv(pow(x, 3, q), q))
        # The source has duplicate oriented rows; keep the first instance of
        # the same visible eigenspace point and target.
        key = (u, v, z.a, z.b, int(bits.d3), 0 if bits.d4 is None else int(bits.d4))
        if key in seen:
            stats["duplicate_eigenspace_row"] += 1
            continue
        seen.add(key)
        rows.append(
            EigenspaceRow(
                x=x,
                w=w,
                t=t,
                u=u,
                v=v,
                z=z,
                d3=int(bits.d3),
                d4=None if bits.d4 not in (-1, 1) else int(bits.d4),
            )
        )
    stats["rows"] = len(rows)
    stats["d3_plus"] = sum(1 for row in rows if row.d3 == 1)
    stats["d3_minus"] = sum(1 for row in rows if row.d3 == -1)
    stats["d4_rows"] = sum(1 for row in rows if row.d4 in (-1, 1))
    stats["d4_plus"] = sum(1 for row in rows if row.d4 == 1)
    stats["d4_minus"] = sum(1 for row in rows if row.d4 == -1)
    return rows, stats


@dataclass(frozen=True)
class Score:
    good: int
    total: int
    zeros: int
    polarity: int
    name: str


def score_packet(rows: list[EigenspaceRow], target: str, packet_name: str, packet_fn: Callable[[EigenspaceRow], Fq2]) -> Score:
    good_plus = 0
    good_minus = 0
    total = 0
    zeros = 0
    for row in rows:
        target_value = row.d3 if target == "d3" else row.d4
        if target_value not in (-1, 1):
            continue
        chi = fq2_chi(packet_fn(row))
        if chi == 0:
            zeros += 1
            continue
        total += 1
        if chi == target_value:
            good_plus += 1
        if chi == -target_value:
            good_minus += 1
    if good_plus >= good_minus:
        return Score(good_plus, total, zeros, 1, packet_name)
    return Score(good_minus, total, zeros, -1, packet_name)


def screen(rows: list[EigenspaceRow], target: str, top: int) -> tuple[Counter[str], list[Score], list[Score]]:
    stats: Counter[str] = Counter()
    best: list[Score] = []
    exact: list[Score] = []
    names_seen: set[str] = set()
    for row in rows[:1]:
        for name, _value in eigenspace_packets(row):
            names_seen.add(name)
    # Packet names depend only on the feature list, not on row values.
    packet_names = sorted(names_seen)
    for name in packet_names:
        def packet_fn(row: EigenspaceRow, name: str = name) -> Fq2:
            for packet_name, value in eigenspace_packets(row):
                if packet_name == name:
                    return value
            return fq2(row.z.q, 0)

        score = score_packet(rows, target, name, packet_fn)
        best.append(score)
        if score.total and score.zeros == 0 and score.good == score.total:
            exact.append(score)
    best.sort(key=lambda item: (item.good / item.total if item.total else 0.0, item.good, -item.zeros), reverse=True)
    exact.sort(key=lambda item: item.name)
    stats["packet_names"] = len(packet_names)
    stats["exact_packets"] = len(exact)
    stats["target"] = 3 if target == "d3" else 4
    stats["rows"] = sum(1 for row in rows if (row.d3 if target == "d3" else row.d4) in (-1, 1))
    stats["best_good"] = best[0].good if best else 0
    stats["best_total"] = best[0].total if best else 0
    stats["best_zeros"] = best[0].zeros if best else 0
    return stats, best[:top], exact[:top]


def print_counter(prefix: str, stats: Counter[str]) -> None:
    print(f"{prefix}:")
    for key in sorted(stats):
        print(f"  {key} = {stats[key]}")


def print_scores(prefix: str, scores: list[Score]) -> None:
    print(f"{prefix}:")
    for score in scores:
        rate = score.good / score.total if score.total else 0.0
        print(
            f"  good={score.good}/{score.total} rate={rate:.9f} "
            f"zeros={score.zeros} polarity={score.polarity} packet={score.name}"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--small-primes", default="607,1471,1607,1847")
    parser.add_argument("--top", type=int, default=12)
    args = parser.parse_args()

    print("p27 E-prime twisted eigenspace screen")
    print("j^2=-1, Z=T*(1-j/X^3), sigma(Z)=jZ")
    print("screen = quadratic characters over F_{q^2} of named Z/Z2/Z4 packets")
    for q in [int(part) for part in args.small_primes.split(",") if part.strip()]:
        rows, stats = collect_rows(q)
        print(f"q={q}:")
        print_counter("  row_stats", stats)
        for target in ("d3", "d4"):
            screen_stats, best, exact = screen(rows, target, args.top)
            print_counter(f"  {target}_screen_stats", screen_stats)
            print_scores(f"  {target}_best_packets", best)
            print_scores(f"  {target}_exact_packets", exact)
    print("p27_eprime_twisted_eigenspace_screen_rows=1/1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
