#!/usr/bin/env python3
"""Visible residual-E character screen for the p27 label-2 compactD bit.

The order-4 lift shows that compactD is a cyclic-quartic character over the
residual elliptic curve E: W^2 = X^3-X.  This probe asks whether that character
already collapses to a visible quadratic character on E generated by the
natural factors from the H90 identity.

It is intentionally narrow: it screens named divisor factors, not arbitrary
high-degree fitting.
"""

from __future__ import annotations

from itertools import combinations


PRIMES = [
    17, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67,
    71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113,
    127, 131, 137, 139, 149, 151, 157, 163, 167, 173,
    179, 181, 191, 193, 197, 199,
]


def legendre(a: int, p: int) -> int:
    a %= p
    if a == 0:
        return 0
    r = pow(a, (p - 1) // 2, p)
    return 1 if r == 1 else -1


def roots(a: int, p: int) -> list[int]:
    a %= p
    return [x for x in range(p) if x * x % p == a]


def f_scalar(x: int, p: int) -> int:
    return (x * x * x - x) % p


def t2_scalar(x: int, p: int) -> int:
    x2 = x * x % p
    return x * (x2 + 1) * (x2 + 2 * x - 1) % p


def compact_parts_scalar(x: int, w: int, p: int) -> tuple[int, int]:
    x2 = x * x % p
    mt = (x + 1) * (2 * w * x + x**3 + x2 - x - 1) % p
    m0 = (x2 + 1) * (x2 + 2 * x - 1) * (w * x + w + 2 * x2) % p
    return mt, m0


def h_scalar(x: int, w: int, t: int, p: int) -> int:
    mt, m0 = compact_parts_scalar(x, w, p)
    return w * (x * x + 1) * (m0 + mt * t) * pow(x, p - 2, p) % p


def feature_values(x: int, w: int, p: int) -> dict[str, int]:
    x2 = x * x % p
    x3 = x2 * x % p
    s = (w * (x + 1) + 2 * x2) % p
    sm = (w * (x + 1) - 2 * x2) % p
    mtlin = (2 * w * x + x3 + x2 - x - 1) % p
    m0 = (x2 + 1) * (x2 + 2 * x - 1) * s % p
    mt = (x + 1) * mtlin % p
    pref = w * (x2 + 1) * pow(x, p - 2, p) % p
    linear_l = (4 * w * x2 + 4 * w * x + x2 * x2 + 6 * x3 - 2 * x - 1) % p
    return {
        "X": x,
        "W": w,
        "X-1": x - 1,
        "X+1": x + 1,
        "X2+1": x2 + 1,
        "X2+2X-1": x2 + 2 * x - 1,
        "X2-2X-1": x2 - 2 * x - 1,
        "S": s,
        "S_conj": sm,
        "mt_linear": mtlin,
        "m0": m0,
        "mt_coeff": mt,
        "prefactor": pref,
        "L": linear_l,
    }


FEATURES = [
    "X",
    "W",
    "X-1",
    "X+1",
    "X2+1",
    "X2+2X-1",
    "X2-2X-1",
    "S",
    "S_conj",
    "mt_linear",
    "m0",
    "mt_coeff",
    "prefactor",
    "L",
]


def bit_pm1(v: int) -> int:
    if v == 1:
        return 0
    if v == -1:
        return 1
    raise ValueError(v)


def collect_rows(p: int) -> tuple[list[tuple[int, int]], dict[str, int]]:
    rows: list[tuple[int, int]] = []
    stats = {
        "base_E_points": 0,
        "t2_square_points": 0,
        "target_plus": 0,
        "target_minus": 0,
        "t_sign_mismatch": 0,
        "zero_feature_skips": 0,
        "zero_target_skips": 0,
    }
    for x in range(1, p):
        for w in roots(f_scalar(x, p), p):
            stats["base_E_points"] += 1
            t2 = t2_scalar(x, p)
            ts = roots(t2, p)
            if not ts:
                continue
            stats["t2_square_points"] += 1
            h_classes = [legendre(h_scalar(x, w, t, p), p) for t in ts]
            if any(c == 0 for c in h_classes):
                stats["zero_target_skips"] += 1
                continue
            if len(set(h_classes)) != 1:
                stats["t_sign_mismatch"] += 1
                continue
            target = h_classes[0]
            if target == 1:
                stats["target_plus"] += 1
            else:
                stats["target_minus"] += 1

            vals = feature_values(x, w, p)
            chars = []
            skip = False
            for name in FEATURES:
                c = legendre(vals[name], p)
                if c == 0:
                    skip = True
                    break
                chars.append(bit_pm1(c))
            if skip:
                stats["zero_feature_skips"] += 1
                continue
            mask = 0
            for i, b in enumerate(chars):
                mask |= b << i
            rows.append((mask, bit_pm1(target)))
    return rows, stats


def combo_name(mask: int) -> str:
    names = [FEATURES[i] for i in range(len(FEATURES)) if (mask >> i) & 1]
    return " * ".join(names) if names else "1"


def popcount(n: int) -> int:
    return bin(n).count("1")


def find_exact_combo(rows: list[tuple[int, int]]) -> int | None:
    if not rows:
        return None
    for combo in range(1 << len(FEATURES)):
        ok = True
        for mask, target in rows:
            if (popcount(mask & combo) & 1) != target:
                ok = False
                break
        if ok:
            return combo
    return None


def best_combos(rows: list[tuple[int, int]], limit: int = 8) -> list[tuple[int, int, int]]:
    scored = []
    for combo in range(1 << len(FEATURES)):
        good = 0
        for mask, target in rows:
            good += ((popcount(mask & combo) & 1) == target)
        scored.append((good, popcount(combo), combo))
    scored.sort(key=lambda item: (-item[0], item[1], item[2]))
    return scored[:limit]


def main() -> int:
    print("p27 label2 visible residual-E character probe")
    print("features = " + ", ".join(FEATURES))
    all_rows: list[tuple[int, int]] = []
    for p in PRIMES:
        rows, stats = collect_rows(p)
        all_rows.extend(rows)
        exact = find_exact_combo(rows)
        print(
            "prime_summary "
            f"p={p} rows={len(rows)} base_E={stats['base_E_points']} "
            f"t2_square={stats['t2_square_points']} target_plus={stats['target_plus']} "
            f"target_minus={stats['target_minus']} zero_feature_skips={stats['zero_feature_skips']} "
            f"zero_target_skips={stats['zero_target_skips']} t_sign_mismatch={stats['t_sign_mismatch']} "
            f"exact={combo_name(exact) if exact is not None else 'none'}"
        )

    exact_all = find_exact_combo(all_rows)
    print(f"combined_rows = {len(all_rows)}")
    print(f"combined_exact_combo = {combo_name(exact_all) if exact_all is not None else 'none'}")
    print("combined_best_combos:")
    for good, weight, combo in best_combos(all_rows):
        rate = good / len(all_rows) if all_rows else 0.0
        print(f"  good={good}/{len(all_rows)} rate={rate:.9f} weight={weight} combo={combo_name(combo)}")
    print("p27_label2_visible_e_character_probe_rows=1/1")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
