#!/usr/bin/env python3
"""Raw/Kummer producer contract for p25 Hilbert-90 source chains.

The source-chain Fourier gate says spectral zeros do not select the active
nonsplit C_169 lift.  This gate moves one step closer to producer-side
arithmetic: it lifts the pinned support-three chains, their four-point first
boundaries, and the final bridge into the raw C_12675 source harness, then
scans the invisible C_25 kernel gauges of the sparse source-chain directions.

The useful conclusion is that the raw right side can be made cheap, but the
C-axis cannot.  For every sparse direction generated by the active chains,
some kernel gauge lowers the right-source order to 3, but every gauge keeps a
primitive C_169 source multiplier and C_169 Kummer degree 169.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from math import gcd

from p25_laneB_divisor_footprint_gate import primitive_root
from p25_laneB_kummer_sign_descent_gate import kummer_class
from p25_laneB_square_axis_bridge_hilbert90_source_boundary_gate import (
    boundary,
    inversion_boundary,
)
from p25_laneB_square_axis_bridge_hilbert90_source_chain_coefficient_rigidity_gate import (
    coefficient_rigidity_profile,
)
from p25_laneB_square_axis_bridge_raw_source_character_gate import (
    C_ORDER,
    MODULUS,
    RIGHT_ORDER,
)
from p25_laneB_square_axis_bridge_raw_source_gate import (
    kernel_mode_support,
    normalized_trace,
    source_generators,
    square_axis_case,
)
from p25_laneB_square_axis_group_ring_normal_form_gate import S_STEP, Y_STEP
from p25_laneB_square_axis_local_graph_residue_gate import QUOTIENT_ORDER


Poly = dict[int, int]


@dataclass(frozen=True)
class RawStageProfile:
    orientation_mask: int
    boundary_direction_q: int
    stage: str
    quotient_support: int
    raw_support: int
    quotient_degree: int
    raw_degree: int
    trace_correct: bool
    block_constancy_hits: int
    kernel_modes: tuple[int, ...]
    kernel_mode0_count: int
    raw_relation_mismatches: int


@dataclass(frozen=True)
class KernelGaugeDirectionProfile:
    direction_q: int
    direction_coord: tuple[int, int]
    kernel_lift_count: int
    right_order_histogram: tuple[tuple[int, int], ...]
    c_order_values: tuple[int, ...]
    combined_order_min: int
    best_raw_shift: int
    best_right_shift: int
    best_c_shift: int
    right_c75_min_degrees: tuple[int, ...]
    right_c3_min_degrees: tuple[int, ...]
    c_c169_min_degrees: tuple[int, ...]
    c_c13_min_degrees: tuple[int, ...]


@dataclass(frozen=True)
class RawKummerProfile:
    raw_stage_rows: tuple[RawStageProfile, ...]
    direction_rows: tuple[KernelGaugeDirectionProfile, ...]
    stage_row_count: int
    all_stage_rows_trace_correct: bool
    all_stage_rows_kernel_trivial: bool
    all_stage_rows_block_constant: bool
    all_stage_rows_raw_relation_compatible: bool
    chain_raw_degrees: tuple[int, ...]
    first_boundary_raw_supports: tuple[int, ...]
    bridge_raw_supports: tuple[int, ...]
    sparse_direction_count: int
    all_sparse_directions_have_primitive_c169_cost: bool
    all_sparse_directions_have_kernel_gauge_right_order_three: bool
    all_sparse_directions_have_min_combined_order_507: bool


def signed_mod(value: int) -> int:
    value %= MODULUS
    return value if value <= MODULUS // 2 else value - MODULUS


def coord_from_q(q_value: int) -> tuple[int, int]:
    return (q_value % 3, q_value % C_ORDER)


def raw_block_lift(poly: Poly) -> list[int]:
    case = square_axis_case()
    raw = [0] * case.raw_order
    for q_value, coefficient in poly.items():
        for layer in range(case.b_trace):
            raw[q_value + QUOTIENT_ORDER * layer] = coefficient % MODULUS
    return raw


def trace_correct(raw: list[int], poly: Poly) -> bool:
    case = square_axis_case()
    trace = normalized_trace(raw, case, MODULUS)
    expected = [poly.get(q_value, 0) % MODULUS for q_value in range(QUOTIENT_ORDER)]
    return all(value == target for value, target in zip(trace, expected))


def block_constancy_hits(raw: list[int]) -> int:
    case = square_axis_case()
    hits = 0
    for q_value in range(QUOTIENT_ORDER):
        values = {raw[q_value + QUOTIENT_ORDER * layer] % MODULUS for layer in range(case.b_trace)}
        hits += int(len(values) == 1)
    return hits


def raw_relation_mismatches(raw: list[int]) -> int:
    mismatches = 0
    for e_value in range(len(raw)):
        if raw[(e_value + 3 * S_STEP) % len(raw)] % MODULUS != raw[(e_value + Y_STEP) % len(raw)] % MODULUS:
            mismatches += 1
    return mismatches


def raw_stage_profile(
    orientation_mask: int,
    boundary_direction_q: int,
    stage: str,
    poly: Poly,
) -> RawStageProfile:
    case = square_axis_case()
    root = primitive_root(MODULUS)
    zeta_b = pow(root, (MODULUS - 1) // case.b_trace, MODULUS)
    raw = raw_block_lift(poly)
    modes, mode_counts = kernel_mode_support(raw, case, MODULUS, zeta_b)
    return RawStageProfile(
        orientation_mask=orientation_mask,
        boundary_direction_q=boundary_direction_q,
        stage=stage,
        quotient_support=len(poly),
        raw_support=sum(1 for value in raw if value % MODULUS),
        quotient_degree=sum(poly.values()),
        raw_degree=sum(signed_mod(value) for value in raw),
        trace_correct=trace_correct(raw, poly),
        block_constancy_hits=block_constancy_hits(raw),
        kernel_modes=modes,
        kernel_mode0_count=mode_counts[0],
        raw_relation_mismatches=raw_relation_mismatches(raw),
    )


def source_order(shift: int, order: int) -> int:
    return order // gcd(order, shift % order)


def combined_order(right_order: int, c_order: int) -> int:
    return right_order * c_order // gcd(right_order, c_order)


def direction_profile(direction_q: int) -> KernelGaugeDirectionProfile:
    case = square_axis_case()
    right_source = case.right_sources[0]
    c_source = case.c_source
    right_generator, c_generator = source_generators(case)
    right_root = primitive_root(right_source.modulus)
    c_root = primitive_root(c_source.modulus)

    rows: list[tuple[int, int, int, int, int, int, int, int, int]] = []
    for layer in range(case.b_trace):
        raw_shift = (direction_q + QUOTIENT_ORDER * layer) % case.raw_order
        right_shift = raw_shift % RIGHT_ORDER
        c_shift = raw_shift % C_ORDER
        right_multiplier = pow(right_generator, right_shift, right_source.modulus)
        c_multiplier = pow(c_generator, c_shift, c_source.modulus)
        rows.append(
            (
                raw_shift,
                right_shift,
                c_shift,
                source_order(right_shift, RIGHT_ORDER),
                source_order(c_shift, C_ORDER),
                kummer_class("right_c75", right_multiplier, RIGHT_ORDER, right_source.modulus, right_root).minimal_extension_degree,
                kummer_class("right_c3", right_multiplier, 3, right_source.modulus, right_root).minimal_extension_degree,
                kummer_class("c_c169", c_multiplier, C_ORDER, c_source.modulus, c_root).minimal_extension_degree,
                kummer_class("c_c13", c_multiplier, 13, c_source.modulus, c_root).minimal_extension_degree,
            )
        )

    best = min(rows, key=lambda row: (combined_order(row[3], row[4]), row[3], row[4], row[0]))
    return KernelGaugeDirectionProfile(
        direction_q=direction_q,
        direction_coord=coord_from_q(direction_q),
        kernel_lift_count=len(rows),
        right_order_histogram=tuple(sorted(Counter(row[3] for row in rows).items())),
        c_order_values=tuple(sorted({row[4] for row in rows})),
        combined_order_min=combined_order(best[3], best[4]),
        best_raw_shift=best[0],
        best_right_shift=best[1],
        best_c_shift=best[2],
        right_c75_min_degrees=tuple(sorted({row[5] for row in rows})),
        right_c3_min_degrees=tuple(sorted({row[6] for row in rows})),
        c_c169_min_degrees=tuple(sorted({row[7] for row in rows})),
        c_c13_min_degrees=tuple(sorted({row[8] for row in rows})),
    )


def sparse_pair_directions() -> tuple[int, ...]:
    directions: set[int] = set()
    for row in coefficient_rigidity_profile().rows:
        for left in row.q_values:
            for right in row.q_values:
                if left != right:
                    directions.add((right - left) % QUOTIENT_ORDER)
    return tuple(sorted(directions))


def raw_kummer_profile() -> RawKummerProfile:
    stage_rows: list[RawStageProfile] = []
    for row in coefficient_rigidity_profile().rows:
        chain = dict(zip(row.q_values, row.recorded_coefficients))
        first_boundary = boundary(chain, row.boundary_direction_q)
        bridge_image = inversion_boundary(first_boundary)
        stage_rows.extend(
            (
                raw_stage_profile(row.orientation_mask, row.boundary_direction_q, "chain", chain),
                raw_stage_profile(row.orientation_mask, row.boundary_direction_q, "first_boundary", first_boundary),
                raw_stage_profile(row.orientation_mask, row.boundary_direction_q, "bridge_image", bridge_image),
            )
        )
    direction_rows = tuple(direction_profile(direction) for direction in sparse_pair_directions())
    return RawKummerProfile(
        raw_stage_rows=tuple(stage_rows),
        direction_rows=direction_rows,
        stage_row_count=len(stage_rows),
        all_stage_rows_trace_correct=all(row.trace_correct for row in stage_rows),
        all_stage_rows_kernel_trivial=all(row.kernel_modes == (0,) for row in stage_rows),
        all_stage_rows_block_constant=all(row.block_constancy_hits == QUOTIENT_ORDER for row in stage_rows),
        all_stage_rows_raw_relation_compatible=all(row.raw_relation_mismatches == 0 for row in stage_rows),
        chain_raw_degrees=tuple(row.raw_degree for row in stage_rows if row.stage == "chain"),
        first_boundary_raw_supports=tuple(row.raw_support for row in stage_rows if row.stage == "first_boundary"),
        bridge_raw_supports=tuple(row.raw_support for row in stage_rows if row.stage == "bridge_image"),
        sparse_direction_count=len(direction_rows),
        all_sparse_directions_have_primitive_c169_cost=all(
            row.c_order_values == (C_ORDER,)
            and row.c_c169_min_degrees == (C_ORDER,)
            and row.c_c13_min_degrees == (13,)
            for row in direction_rows
        ),
        all_sparse_directions_have_kernel_gauge_right_order_three=all(
            row.right_order_histogram == ((3, 1), (15, 4), (75, 20))
            for row in direction_rows
        ),
        all_sparse_directions_have_min_combined_order_507=all(
            row.combined_order_min == QUOTIENT_ORDER for row in direction_rows
        ),
    )


def main() -> int:
    print("p25 Lane B square-axis bridge Hilbert-90 source-chain raw/Kummer gate")
    profile = raw_kummer_profile()
    expected_directions = (
        KernelGaugeDirectionProfile(25, (1, 25), 25, ((3, 1), (15, 4), (75, 20)), (169,), 507, 25, 25, 25, (3, 15, 75), (3,), (169,), (13,)),
        KernelGaugeDirectionProfile(172, (1, 3), 25, ((3, 1), (15, 4), (75, 20)), (169,), 507, 2200, 25, 3, (3, 15, 75), (3,), (169,), (13,)),
        KernelGaugeDirectionProfile(197, (2, 28), 25, ((3, 1), (15, 4), (75, 20)), (169,), 507, 2225, 50, 28, (3, 15, 75), (3,), (169,), (13,)),
        KernelGaugeDirectionProfile(310, (1, 141), 25, ((3, 1), (15, 4), (75, 20)), (169,), 507, 10450, 25, 141, (3, 15, 75), (3,), (169,), (13,)),
        KernelGaugeDirectionProfile(335, (2, 166), 25, ((3, 1), (15, 4), (75, 20)), (169,), 507, 10475, 50, 166, (3, 15, 75), (3,), (169,), (13,)),
        KernelGaugeDirectionProfile(482, (2, 144), 25, ((3, 1), (15, 4), (75, 20)), (169,), 507, 12650, 50, 144, (3, 15, 75), (3,), (169,), (13,)),
    )
    row_ok = (
        profile.stage_row_count == 12
        and profile.all_stage_rows_trace_correct
        and profile.all_stage_rows_kernel_trivial
        and profile.all_stage_rows_block_constant
        and profile.all_stage_rows_raw_relation_compatible
        and profile.chain_raw_degrees == (-75, 75, -75, 75)
        and profile.first_boundary_raw_supports == (100, 100, 100, 100)
        and profile.bridge_raw_supports == (150, 150, 150, 150)
        and profile.sparse_direction_count == 6
        and profile.direction_rows == expected_directions
        and profile.all_sparse_directions_have_primitive_c169_cost
        and profile.all_sparse_directions_have_kernel_gauge_right_order_three
        and profile.all_sparse_directions_have_min_combined_order_507
    )

    print(
        "raw_stage_summary: "
        f"stage_row_count={profile.stage_row_count} "
        f"trace_correct={int(profile.all_stage_rows_trace_correct)} "
        f"kernel_trivial={int(profile.all_stage_rows_kernel_trivial)} "
        f"block_constant={int(profile.all_stage_rows_block_constant)} "
        f"raw_relation_compatible={int(profile.all_stage_rows_raw_relation_compatible)} "
        f"chain_raw_degrees={profile.chain_raw_degrees} "
        f"first_boundary_raw_supports={profile.first_boundary_raw_supports} "
        f"bridge_raw_supports={profile.bridge_raw_supports}"
    )
    print("raw_stage_rows")
    for row in profile.raw_stage_rows:
        print(f"  {row}")
    print(
        "kernel_gauge_direction_summary: "
        f"sparse_direction_count={profile.sparse_direction_count} "
        f"primitive_c169_cost={int(profile.all_sparse_directions_have_primitive_c169_cost)} "
        f"right_order_three_available={int(profile.all_sparse_directions_have_kernel_gauge_right_order_three)} "
        f"min_combined_order_507={int(profile.all_sparse_directions_have_min_combined_order_507)}"
    )
    print("kernel_gauge_direction_rows")
    for row in profile.direction_rows:
        print(f"  {row}")
    print("interpretation")
    print("  active_chains_have_kernel_trivial_raw_lifts_but_nonzero_raw_degree=1")
    print("  first_boundaries_are_degree_zero_kernel_trivial_raw_potentials_with_support_100=1")
    print("  bridge_images_are_degree_zero_kernel_trivial_raw_bridge_lifts_with_support_150=1")
    print("  invisible_C25_kernel_gauge_can_lower_the_right_source_order_to_3=1")
    print("  every_sparse_source_chain_direction_still_has_primitive_C169_order_and_Kummer_degree_169=1")
    print("  producer_must_realize_the_primitive_C169_motion_not_only_a_cheap_right_kernel_gauge=1")
    print(f"square_axis_bridge_hilbert90_source_chain_raw_kummer_rows={int(row_ok)}/1")
    print("conclusion=reported_p25_laneB_square_axis_bridge_hilbert90_source_chain_raw_kummer_gate")
    return 0 if row_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
