#!/usr/bin/env python3
"""Doubling-orbit norm form of the conductor-39 coset quotient.

The coset-selector gate writes

    Q = prod_{h in <2>} E_{7h}/E_h.

Since <2> is generated by doubling modulo 39, Q is also the 12-step orbit norm
of the seed ratio E_7/E_1 under h -> 2h.  This is a sharper theorem-facing
producer: emit one seed ratio and the full doubling orbit norm.
"""

from __future__ import annotations

from dataclasses import dataclass

from p25_ksy_y_yang_y507_conductor39_coset_frobenius_pairing_gate import (
    ordered_coset,
    ordered_kernel,
    profile_yang_y507_conductor39_coset_frobenius_pairing,
)
from p25_ksy_y_yang_y507_conductor39_coset_selector_gate import (
    COSET_REPRESENTATIVE,
    GENERATOR,
    coset_quotient_word,
    profile_yang_y507_conductor39_coset_selector,
)
from p25_ksy_y_yang_y507_conductor39_frobenius_contract_gate import P25
from p25_ksy_y_yang_y507_conductor39_primitive_character_unit_gate import (
    primitive_word,
)
from p25_ksy_y_yang_y507_period_norm_conductor_gate import CONDUCTOR


ORBIT_LENGTH = 12


@dataclass(frozen=True)
class SeedOrbitRow:
    index: int
    multiplier: int
    denominator: int
    numerator: int
    word: tuple[tuple[int, int], ...]
    frob_numerator_index: int
    frob_denominator_index: int
    ok: bool


@dataclass(frozen=True)
class Conductor39DoublingOrbitNorm:
    level: int
    generator: int
    orbit_length: int
    seed_denominator: int
    seed_numerator: int
    seed_word: tuple[tuple[int, int], ...]
    seed_orbit_rows: tuple[SeedOrbitRow, ...]
    orbit_norm_word: tuple[tuple[int, int], ...]
    orbit_norm_equals_coset_quotient: bool
    orbit_norm_equals_primitive_unit: bool
    orbit_support: int
    seed_support_total_before_cancellation: int
    no_cancellation_in_orbit_norm: bool
    frob_seed_maps_to_skew_inverse_pair: bool
    frob_orbit_norm_is_inverse: bool
    p_denominator_shift_to_numerator: int
    p_numerator_shift_to_denominator: int
    single_seed_ratio_descends: bool
    full_orbit_required: bool
    coset_selector_ok: bool
    coset_pairing_ok: bool
    direct_closer: bool
    positive_payload: str
    first_missing_clause: str
    recommendation: str
    row_ok: bool


def add_words(left: dict[int, int], right: dict[int, int]) -> dict[int, int]:
    out = dict(left)
    for residue, coefficient in right.items():
        out[residue] = out.get(residue, 0) + coefficient
    return dict(sorted((residue, coefficient) for residue, coefficient in out.items() if coefficient))


def seed_word() -> dict[int, int]:
    return {COSET_REPRESENTATIVE: 1, 1: -1}


def multiply_word(word: dict[int, int], multiplier: int) -> dict[int, int]:
    out: dict[int, int] = {}
    for residue, coefficient in word.items():
        target = (multiplier * residue) % CONDUCTOR
        out[target] = out.get(target, 0) + coefficient
    return dict(sorted((residue, coefficient) for residue, coefficient in out.items() if coefficient))


def orbit_norm_word() -> dict[int, int]:
    out: dict[int, int] = {}
    for index in range(ORBIT_LENGTH):
        out = add_words(out, multiply_word(seed_word(), pow(GENERATOR, index, CONDUCTOR)))
    return out


def ordered_index(value: int, cycle: tuple[int, ...]) -> int:
    try:
        return cycle.index(value)
    except ValueError as exc:
        raise AssertionError(f"value {value} missing from cycle") from exc


def seed_orbit_rows() -> tuple[SeedOrbitRow, ...]:
    kernel = ordered_kernel()
    coset = ordered_coset()
    rows: list[SeedOrbitRow] = []
    for index, denominator in enumerate(kernel):
        multiplier = pow(GENERATOR, index, CONDUCTOR)
        word = multiply_word(seed_word(), multiplier)
        numerator = (COSET_REPRESENTATIVE * denominator) % CONDUCTOR
        frob_denominator = (P25 * denominator) % CONDUCTOR
        frob_numerator = (P25 * numerator) % CONDUCTOR
        rows.append(
            SeedOrbitRow(
                index=index,
                multiplier=multiplier,
                denominator=denominator,
                numerator=numerator,
                word=tuple(sorted(word.items())),
                frob_numerator_index=ordered_index(frob_denominator, coset),
                frob_denominator_index=ordered_index(frob_numerator, kernel),
                ok=(
                    word == {denominator: -1, numerator: 1}
                    and ordered_index(frob_denominator, coset) == (index + 11) % ORBIT_LENGTH
                    and ordered_index(frob_numerator, kernel) == (index + 9) % ORBIT_LENGTH
                ),
            )
        )
    return tuple(rows)


def negative_word(word: dict[int, int]) -> dict[int, int]:
    return {residue: -coefficient for residue, coefficient in word.items()}


def push_frobenius(word: dict[int, int]) -> dict[int, int]:
    return multiply_word(word, P25 % CONDUCTOR)


def profile_yang_y507_conductor39_doubling_orbit_norm() -> Conductor39DoublingOrbitNorm:
    coset = profile_yang_y507_conductor39_coset_selector()
    pairing = profile_yang_y507_conductor39_coset_frobenius_pairing()
    kernel = ordered_kernel()
    coset_cycle = ordered_coset()
    rows = seed_orbit_rows()
    norm = orbit_norm_word()
    quotient = coset_quotient_word(tuple(sorted(kernel)), tuple(sorted(coset_cycle)))
    primitive = primitive_word()
    direct_closer = False
    single_seed_descends = push_frobenius(seed_word()) == negative_word(seed_word())
    row_ok = (
        coset.row_ok
        and pairing.row_ok
        and CONDUCTOR == 39
        and GENERATOR == 2
        and COSET_REPRESENTATIVE == 7
        and ORBIT_LENGTH == 12
        and len(rows) == ORBIT_LENGTH
        and all(row.ok for row in rows)
        and norm == quotient
        and norm == primitive
        and len(norm) == 24
        and 2 * ORBIT_LENGTH == 24
        and push_frobenius(norm) == negative_word(norm)
        and not single_seed_descends
        and not direct_closer
    )
    return Conductor39DoublingOrbitNorm(
        level=CONDUCTOR,
        generator=GENERATOR,
        orbit_length=ORBIT_LENGTH,
        seed_denominator=1,
        seed_numerator=COSET_REPRESENTATIVE,
        seed_word=tuple(sorted(seed_word().items())),
        seed_orbit_rows=rows,
        orbit_norm_word=tuple(sorted(norm.items())),
        orbit_norm_equals_coset_quotient=norm == quotient,
        orbit_norm_equals_primitive_unit=norm == primitive,
        orbit_support=len(norm),
        seed_support_total_before_cancellation=2 * ORBIT_LENGTH,
        no_cancellation_in_orbit_norm=len(norm) == 2 * ORBIT_LENGTH,
        frob_seed_maps_to_skew_inverse_pair=True,
        frob_orbit_norm_is_inverse=push_frobenius(norm) == negative_word(norm),
        p_denominator_shift_to_numerator=pairing.denominator_to_numerator_shift,
        p_numerator_shift_to_denominator=pairing.numerator_to_denominator_shift,
        single_seed_ratio_descends=single_seed_descends,
        full_orbit_required=not single_seed_descends and push_frobenius(norm) == negative_word(norm),
        coset_selector_ok=coset.row_ok,
        coset_pairing_ok=pairing.row_ok,
        direct_closer=direct_closer,
        positive_payload=(
            "Q is the 12-step doubling-orbit norm of the seed ratio E_7/E_1."
        ),
        first_missing_clause=(
            "orbit-norm structure is not the finite-field value/divisor theorem "
            "or DANGER3 extraction"
        ),
        recommendation=(
            "ask source theorems for a doubling-orbit norm of E_7/E_1; reject "
            "single-seed descents because Frobenius maps the seed ratio to a "
            "skew inverse pair, not its own inverse"
        ),
        row_ok=row_ok,
    )


def main() -> int:
    profile = profile_yang_y507_conductor39_doubling_orbit_norm()
    print("p25 KSY-y Yang Y_507 conductor-39 doubling-orbit norm gate")
    print(f"level={profile.level}")
    print(f"generator={profile.generator}")
    print(f"orbit_length={profile.orbit_length}")
    print(f"seed_denominator={profile.seed_denominator}")
    print(f"seed_numerator={profile.seed_numerator}")
    print(f"seed_word={profile.seed_word}")
    print("sample_seed_orbit_rows")
    for row in profile.seed_orbit_rows[:4]:
        print(
            "  "
            f"i={row.index} multiplier={row.multiplier} den={row.denominator} "
            f"num={row.numerator} word={row.word} "
            f"Fden_to_num_i={row.frob_numerator_index} "
            f"Fnum_to_den_i={row.frob_denominator_index} ok={int(row.ok)}"
        )
    print("checks")
    print(f"  orbit_norm_equals_coset_quotient={int(profile.orbit_norm_equals_coset_quotient)}")
    print(f"  orbit_norm_equals_primitive_unit={int(profile.orbit_norm_equals_primitive_unit)}")
    print(f"  orbit_support={profile.orbit_support}")
    print(f"  seed_support_total_before_cancellation={profile.seed_support_total_before_cancellation}")
    print(f"  no_cancellation_in_orbit_norm={int(profile.no_cancellation_in_orbit_norm)}")
    print(f"  frob_seed_maps_to_skew_inverse_pair={int(profile.frob_seed_maps_to_skew_inverse_pair)}")
    print(f"  frob_orbit_norm_is_inverse={int(profile.frob_orbit_norm_is_inverse)}")
    print(f"  p_denominator_shift_to_numerator={profile.p_denominator_shift_to_numerator}")
    print(f"  p_numerator_shift_to_denominator={profile.p_numerator_shift_to_denominator}")
    print(f"  single_seed_ratio_descends={int(profile.single_seed_ratio_descends)}")
    print(f"  full_orbit_required={int(profile.full_orbit_required)}")
    print(f"  coset_selector_ok={int(profile.coset_selector_ok)}")
    print(f"  coset_pairing_ok={int(profile.coset_pairing_ok)}")
    print(f"  direct_closer={int(profile.direct_closer)}")
    print("interpretation")
    print("  Q_is_doubling_orbit_norm_of_E7_over_E1=1")
    print("  single_seed_ratio_does_not_descend_by_itself=1")
    print("  full_12_step_orbit_norm_has_Frob_p_Q_equals_Q_inverse=1")
    print("  still_missing_value_or_divisor_theorem_and_DANGER3_extraction=1")
    print(
        "ksy_y_yang_y507_conductor39_doubling_orbit_norm_rows="
        f"{int(profile.row_ok)}/1"
    )
    if not profile.row_ok:
        raise SystemExit("Yang Y_507 conductor-39 doubling-orbit norm regression failed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
