#!/usr/bin/env python3
"""Koo-Shin-Yoon primary-source scout for the exact p25 KSY-y product.

This gate records the result of checking arXiv:1007.2307 against the current
closing-theorem obligation.  The paper supplies the normalized y/Siegel-function
language, but its stated ray-class generation theorems do not emit the exact
p25 mixed product P.
"""

from __future__ import annotations

from dataclasses import dataclass

from p25_laneB_robert_ksy_theta2_kubert_lang_ksy_y_source_claim_intake_gate import (
    SourceClaim,
    classify_claim,
)


@dataclass(frozen=True)
class KsySourceObservation:
    name: str
    paper_clause: str
    source_handle: str
    claim: SourceClaim
    expected_decision: str
    matched_clause: str
    first_missing_clause: str


@dataclass(frozen=True)
class KsyExactPScoutProfile:
    source: str
    observations: tuple[KsySourceObservation, ...]
    formula_language_rows: int
    direct_closing_rows: int
    conditional_rows: int
    rejected_rows: int
    hypothetical_closing_rows: int
    row_ok: bool


SOURCE = "Koo-Shin-Yoon, Ray class fields generated by torsion points of certain elliptic curves"


def observations() -> tuple[KsySourceObservation, ...]:
    return (
        KsySourceObservation(
            name="ksy_equation_3_4_normalized_y",
            paper_clause="Equation (3.4)",
            source_handle="arXiv:1007.2307 lines 569-584",
            claim=SourceClaim(
                "ksy_equation_3_4_formula_language",
                "ksy_normalized_y_siegel_formula",
                "value",
                False,
                False,
                False,
                False,
                False,
                False,
            ),
            expected_decision="conditional_missing_exact_product",
            matched_clause="supplies y(r1,r2)=-g(2r1,2r2)/g(r1,r2)^4 formula language",
            first_missing_clause="exact mixed product P over the p25 C,D,K atoms",
        ),
        KsySourceObservation(
            name="ksy_theorem_5_3_ray_class_generation",
            paper_clause="Theorem 5.3",
            source_handle="arXiv:1007.2307 lines 2308-2337",
            claim=SourceClaim(
                "ksy_theorem_5_3_generation_only",
                "ksy_theorem_5_3_ray_class_generation",
                "field-generation",
                False,
                False,
                False,
                False,
                False,
                False,
            ),
            expected_decision="reject_not_closure_theorem",
            matched_clause="single torsion point generates K(N) over K",
            first_missing_clause="not an exact finite-field identity for P",
        ),
        KsySourceObservation(
            name="ksy_corollary_6_4_single_y_value",
            paper_clause="Corollary 6.4",
            source_handle="arXiv:1007.2307 lines 2790-2861",
            claim=SourceClaim(
                "ksy_corollary_6_4_single_y_value",
                "ksy_normalized_y_siegel_formula",
                "value",
                False,
                False,
                False,
                True,
                False,
                False,
            ),
            expected_decision="conditional_missing_exact_product",
            matched_clause="single y(0,1/N)^4 value generator for ray class fields",
            first_missing_clause="exact P and mixed C_3 x C_169 graph selector",
        ),
        KsySourceObservation(
            name="ksy_hypothetical_exact_p_value_without_period",
            paper_clause="not supplied by arXiv:1007.2307; calibration row",
            source_handle="local closing-template requirement",
            claim=SourceClaim(
                "ksy_exact_p_value_without_period",
                "ksy_normalized_y_siegel_formula",
                "value",
                True,
                True,
                False,
                True,
                False,
                False,
            ),
            expected_decision="conditional_missing_period_156_context",
            matched_clause="would supply exact finite-field value for P",
            first_missing_clause="period-156 branch/root/telescoping context",
        ),
        KsySourceObservation(
            name="ksy_hypothetical_exact_p_divisor_identity",
            paper_clause="not supplied by arXiv:1007.2307; calibration row",
            source_handle="local closing-template requirement",
            claim=SourceClaim(
                "ksy_exact_p_divisor_identity",
                "ksy_normalized_y_siegel_formula",
                "divisor-additive",
                True,
                True,
                False,
                False,
                True,
                False,
            ),
            expected_decision="closing_divisor_or_additive_identity",
            matched_clause="would close the source theorem side",
            first_missing_clause="none in source theorem; DANGER3 framing/extraction remains separate",
        ),
    )


def profile_ksy_exact_p_scout() -> KsyExactPScoutProfile:
    rows = observations()
    decisions = tuple(classify_claim(row.claim) for row in rows)
    formula_language_rows = sum(int(row.name == "ksy_equation_3_4_normalized_y") for row in rows)
    direct_closing_rows = sum(
        int(decision.closes_route and not row.name.startswith("ksy_hypothetical_"))
        for row, decision in zip(rows, decisions)
    )
    hypothetical_closing_rows = sum(
        int(decision.closes_route and row.name.startswith("ksy_hypothetical_"))
        for row, decision in zip(rows, decisions)
    )
    rejected_rows = sum(int(decision.decision.startswith("reject_")) for decision in decisions)
    conditional_rows = len(rows) - direct_closing_rows - hypothetical_closing_rows - rejected_rows
    row_ok = (
        formula_language_rows == 1
        and direct_closing_rows == 0
        and conditional_rows == 3
        and rejected_rows == 1
        and hypothetical_closing_rows == 1
        and all(decision.decision == row.expected_decision for row, decision in zip(rows, decisions))
        and decisions[0].first_missing_clause == "exact product P with C=(47,28), D=(22,3), K=(57,0)"
        and decisions[1].first_missing_clause == "not an exact finite-field identity for P"
    )
    return KsyExactPScoutProfile(
        source=SOURCE,
        observations=rows,
        formula_language_rows=formula_language_rows,
        direct_closing_rows=direct_closing_rows,
        conditional_rows=conditional_rows,
        rejected_rows=rejected_rows,
        hypothetical_closing_rows=hypothetical_closing_rows,
        row_ok=row_ok,
    )


def main() -> int:
    profile = profile_ksy_exact_p_scout()
    print("p25 KSY-y Koo-Shin-Yoon exact-P primary-source scout gate")
    print(f"source={profile.source}")
    print("observations")
    for row in profile.observations:
        decision = classify_claim(row.claim)
        print(
            "  "
            f"{row.name}: clause={row.paper_clause} handle={row.source_handle} "
            f"decision={decision.decision} closes={int(decision.closes_route)} "
            f"matched={row.matched_clause} missing={decision.first_missing_clause}"
        )
    print("counts")
    print(f"  formula_language_rows={profile.formula_language_rows}")
    print(f"  direct_closing_rows={profile.direct_closing_rows}")
    print(f"  conditional_rows={profile.conditional_rows}")
    print(f"  rejected_rows={profile.rejected_rows}")
    print(f"  hypothetical_closing_rows={profile.hypothetical_closing_rows}")
    print("interpretation")
    print("  ksy_3_4_formula_language_remains_live=1")
    print("  ksy_theorem_5_3_generation_only_does_not_close=1")
    print("  ksy_corollary_6_4_single_y_value_does_not_close=1")
    print("  exact_P_mixed_graph_is_the_first_missing_clause=1")
    print(f"ksy_y_ksy_exact_p_primary_source_scout_rows={int(profile.row_ok)}/1")
    if not profile.row_ok:
        raise SystemExit("KSY exact-P primary-source scout regression failed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
