#!/usr/bin/env python3
"""Exact edge-lattice minimality for the p25 quotient-C4 source graph.

The edge-lattice intake classifier already routes coefficient-sum-one vectors.
This gate records the global integer-lattice fact behind that routing: among
all integer combinations with W boundary, the only L1-minimal vectors are the
four unit edges.  Every other W-boundary vector is a unit edge plus a nonzero
boundary-zero lattice element and has L1 norm at least 3.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import product
from pathlib import Path


EDGE_NAMES = ("m1", "m2", "m4", "m8")
ZERO_BASIS = (
    (-1, 1, 0, 0),
    (-1, 0, 1, 0),
    (-1, 0, 0, 1),
)


@dataclass(frozen=True)
class EvidenceMarker:
    name: str
    path: Path
    marker: str
    ok: bool


@dataclass(frozen=True)
class MinimalityRow:
    name: str
    statement: str
    decision: str
    ok: bool


@dataclass(frozen=True)
class EdgeLatticeGlobalMinimality:
    evidence_markers: tuple[EvidenceMarker, ...]
    rows: tuple[MinimalityRow, ...]
    zero_lattice_rank: int
    unit_edges: int
    l1_minimal_w_boundary_vectors: int
    bounded_nonunit_min_l1: int
    bounded_decomposition_ok: bool
    current_source_theorems: int
    current_submission_ready: int
    row_ok: bool


def marker(name: str, path: str, needle: str) -> EvidenceMarker:
    p = Path(path)
    text = p.read_text() if p.exists() else ""
    return EvidenceMarker(name=name, path=p, marker=needle, ok=needle in text)


def evidence_markers() -> tuple[EvidenceMarker, ...]:
    return (
        marker(
            "source_graph_normal_form",
            "research/p25/evidence/p25_v2_source_graph_normal_form_20260616.md",
            "p25_v2_source_graph_normal_form_rows=1/1",
        ),
        marker(
            "edge_lattice_intake_classifier",
            "research/p25/evidence/p25_v2_edge_lattice_intake_classifier_20260616.md",
            "p25_v2_edge_lattice_intake_classifier_rows=1/1",
        ),
        marker(
            "partial_projector_selector",
            "research/p25/evidence/p25_v2_partial_projector_selector_20260616.md",
            "p25_v2_partial_projector_selector_rows=1/1",
        ),
        marker(
            "edge_projector_denominator",
            "research/p25/evidence/p25_v2_edge_projector_denominator_20260616.md",
            "p25_v2_edge_projector_denominator_rows=1/1",
        ),
        marker(
            "positive_theorem_clause_matcher",
            "research/p25/evidence/p25_v2_positive_theorem_clause_matcher_20260616.md",
            "p25_v2_positive_theorem_clause_matcher_rows=1/1",
        ),
    )


def coeff_sum(v: tuple[int, int, int, int]) -> int:
    return sum(v)


def l1(v: tuple[int, int, int, int]) -> int:
    return sum(abs(x) for x in v)


def is_unit_edge(v: tuple[int, int, int, int]) -> bool:
    return v in ((1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 0, 1))


def decompose_from_m1(v: tuple[int, int, int, int]) -> tuple[int, int, int]:
    """Return coordinates in v = m1 + a(m2-m1)+b(m4-m1)+c(m8-m1)."""
    return (v[1], v[2], v[3])


def reconstruct_from_m1(coords: tuple[int, int, int]) -> tuple[int, int, int, int]:
    a, b, c = coords
    return (1 - a - b - c, a, b, c)


def rows() -> tuple[MinimalityRow, ...]:
    return (
        MinimalityRow(
            name="boundary_scale_is_coefficient_sum",
            statement="boundary(c1,c2,c4,c8) = (c1+c2+c4+c8) W",
            decision="W_boundary_requires_sum_one",
            ok=True,
        ),
        MinimalityRow(
            name="zero_boundary_lattice_rank_three",
            statement="kernel of coefficient sum is generated by m2-m1, m4-m1, m8-m1",
            decision="boundary_zero_debt_is_rank_three",
            ok=True,
        ),
        MinimalityRow(
            name="unit_edges_are_exact_l1_minima",
            statement="if c is integral, sum(c)=1, and L1(c)=1, then c is one unit edge",
            decision="minimal_W_boundary_vector_is_one_edge",
            ok=True,
        ),
        MinimalityRow(
            name="nonunit_w_boundary_has_l1_at_least_three",
            statement="if c is integral, sum(c)=1, and c is not a unit edge, then L1(c)>=3",
            decision="nonedge_W_boundary_carries_selector_debt",
            ok=True,
        ),
        MinimalityRow(
            name="all_nonunit_w_boundary_vectors_decompose",
            statement="every integral sum-one vector equals one unit edge plus nonzero zero-boundary lattice content",
            decision="repair_edge_plus_boundary_zero_lattice",
            ok=True,
        ),
    )


def build_minimality() -> EdgeLatticeGlobalMinimality:
    markers = evidence_markers()
    rs = rows()
    unit_edges = sum(
        1
        for v in product(range(-2, 3), repeat=4)
        if coeff_sum(v) == 1 and l1(v) == 1 and is_unit_edge(v)
    )
    nonunit_l1_values = [
        l1(v)
        for v in product(range(-2, 3), repeat=4)
        if coeff_sum(v) == 1 and not is_unit_edge(v)
    ]
    bounded_nonunit_min_l1 = min(nonunit_l1_values)
    bounded_decomposition_ok = True
    for v in product(range(-2, 3), repeat=4):
        if coeff_sum(v) != 1:
            continue
        coords = decompose_from_m1(v)
        bounded_decomposition_ok = bounded_decomposition_ok and reconstruct_from_m1(coords) == v
        if not is_unit_edge(v):
            bounded_decomposition_ok = bounded_decomposition_ok and coords != (0, 0, 0)
    current_source_theorems = 0
    current_submission_ready = 0
    row_ok = (
        sum(m.ok for m in markers) == len(markers)
        and len(rs) == 5
        and all(row.ok for row in rs)
        and len(ZERO_BASIS) == 3
        and all(coeff_sum(row) == 0 for row in ZERO_BASIS)
        and unit_edges == 4
        and bounded_nonunit_min_l1 == 3
        and bounded_decomposition_ok
        and current_source_theorems == 0
        and current_submission_ready == 0
    )
    return EdgeLatticeGlobalMinimality(
        evidence_markers=markers,
        rows=rs,
        zero_lattice_rank=len(ZERO_BASIS),
        unit_edges=unit_edges,
        l1_minimal_w_boundary_vectors=unit_edges,
        bounded_nonunit_min_l1=bounded_nonunit_min_l1,
        bounded_decomposition_ok=bounded_decomposition_ok,
        current_source_theorems=current_source_theorems,
        current_submission_ready=current_submission_ready,
        row_ok=row_ok,
    )


def main() -> int:
    minimality = build_minimality()
    print("p25 v2 edge lattice global minimality")
    for marker_row in minimality.evidence_markers:
        print(f"marker {marker_row.name}: {'ok' if marker_row.ok else 'MISSING'}")
    print("rows")
    for row in minimality.rows:
        print(f"  {row.name}: decision={row.decision}")
        print(f"    statement={row.statement}")
    print("counts")
    print(f"  evidence_markers_ok={sum(m.ok for m in minimality.evidence_markers)}/{len(minimality.evidence_markers)}")
    print(f"  zero_lattice_rank={minimality.zero_lattice_rank}")
    print(f"  unit_edges={minimality.unit_edges}")
    print(f"  l1_minimal_w_boundary_vectors={minimality.l1_minimal_w_boundary_vectors}")
    print(f"  bounded_nonunit_min_l1={minimality.bounded_nonunit_min_l1}")
    print(f"  bounded_decomposition_ok={int(minimality.bounded_decomposition_ok)}")
    print(f"  current_source_theorems={minimality.current_source_theorems}")
    print(f"  current_submission_ready={minimality.current_submission_ready}")
    print(f"p25_v2_edge_lattice_global_minimality_rows={int(minimality.row_ok)}/1")
    return 0 if minimality.row_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
