#!/usr/bin/env python3
"""Primitive-D crosswalk for the p25 KSY Kubert-Lang packet.

The CRT-coupling gate identifies the exact graph packet in C3 x C169.  This
gate rewrites that packet in the primitive cyclic coordinate generated by
D=(1,3).  The result is the already-audited bridge product word

    z^121 * (1 + z + z^2) * (1 - z^263)

on C507.  This amortizes the existing primitive-product rigidity work: a
Kubert-Lang/Sprang theorem hit for the graph packet is the same finite target
as the previously classified bridge word, not a new short-product family.
"""

from __future__ import annotations

from dataclasses import dataclass

from p25_laneB_robert_ksy_theta2_kubert_lang_crt_coupling_gate import q_from_coord
from p25_laneB_robert_ksy_theta2_kubert_lang_exponent_matrix_gate import (
    QUOTIENT_LEVEL,
    source_packet,
)
from p25_laneB_square_axis_bridge_primitive_product_rigidity_gate import (
    KERNEL_QUOTIENT_ORDER,
    QuotientProductMatch,
    quotient_product_matches,
)


Coord = tuple[int, int]
Word = dict[int, int]


@dataclass(frozen=True)
class PrimitiveWordProfile:
    d_q_step: int
    d_q_inverse: int
    t_q_step: int
    t_primitive_exponent: int
    base_q: int
    base_primitive_exponent: int
    primitive_support: tuple[tuple[int, int, Coord], ...]
    normalized_support: tuple[tuple[int, int, Coord], ...]
    quotient_word: tuple[tuple[int, int], ...]
    normalized_word: tuple[tuple[int, int], ...]
    product_matches: tuple[QuotientProductMatch, ...]
    forward_factor_law_ok: bool
    inherited_product_rigidity_ok: bool
    next_debt: str
    row_ok: bool


def primitive_exponent(coord: Coord, d_q_inverse: int) -> int:
    return (q_from_coord(coord) * d_q_inverse) % QUOTIENT_LEVEL


def word_from_support(support: tuple[tuple[int, int, Coord], ...]) -> Word:
    return {exponent: coefficient for exponent, coefficient, _coord in support}


def profile_primitive_word() -> PrimitiveWordProfile:
    packet = source_packet()
    d_q_step = q_from_coord((1, 3))
    d_q_inverse = pow(d_q_step, -1, QUOTIENT_LEVEL)
    t_q_step = q_from_coord((2, 113))
    t_primitive_exponent = (t_q_step * d_q_inverse) % QUOTIENT_LEVEL
    base_q = q_from_coord((1, 25))
    base_primitive_exponent = (base_q * d_q_inverse) % QUOTIENT_LEVEL
    primitive_support = tuple(
        sorted(
            (
                primitive_exponent(coord, d_q_inverse),
                coefficient,
                coord,
            )
            for coord, coefficient in packet.items()
        )
    )
    normalized_support = tuple(
        sorted(
            (
                (primitive_exponent(coord, d_q_inverse) - base_primitive_exponent)
                % QUOTIENT_LEVEL,
                coefficient,
                coord,
            )
            for coord, coefficient in packet.items()
        )
    )
    quotient_word = tuple(
        (exponent, coefficient) for exponent, coefficient, _coord in primitive_support
    )
    normalized_word = tuple(
        (exponent, coefficient) for exponent, coefficient, _coord in normalized_support
    )
    product_matches = quotient_product_matches(dict(quotient_word))
    expected_matches = (
        QuotientProductMatch(
            two_direction=244,
            two_sign=-1,
            three_support=(384, 385, 386),
            three_coefficients=(-1, -1, -1),
            is_forward_bridge=False,
            is_reverse_bridge=True,
        ),
        QuotientProductMatch(
            two_direction=263,
            two_sign=-1,
            three_support=(121, 122, 123),
            three_coefficients=(1, 1, 1),
            is_forward_bridge=True,
            is_reverse_bridge=False,
        ),
    )
    forward_factor_law_ok = (
        quotient_word
        == (
            (121, 1),
            (122, 1),
            (123, 1),
            (384, -1),
            (385, -1),
            (386, -1),
        )
        and normalized_word
        == (
            (0, 1),
            (1, 1),
            (2, 1),
            (263, -1),
            (264, -1),
            (265, -1),
        )
        and t_primitive_exponent == 263
    )
    inherited_product_rigidity_ok = product_matches == expected_matches
    row_ok = (
        KERNEL_QUOTIENT_ORDER == QUOTIENT_LEVEL
        and d_q_step == 178
        and d_q_inverse == 94
        and t_q_step == 170
        and base_q == 244
        and base_primitive_exponent == 121
        and primitive_support
        == (
            (121, 1, (1, 25)),
            (122, 1, (2, 28)),
            (123, 1, (0, 31)),
            (384, -1, (0, 138)),
            (385, -1, (1, 141)),
            (386, -1, (2, 144)),
        )
        and normalized_support
        == (
            (0, 1, (1, 25)),
            (1, 1, (2, 28)),
            (2, 1, (0, 31)),
            (263, -1, (0, 138)),
            (264, -1, (1, 141)),
            (265, -1, (2, 144)),
        )
        and forward_factor_law_ok
        and inherited_product_rigidity_ok
    )
    return PrimitiveWordProfile(
        d_q_step=d_q_step,
        d_q_inverse=d_q_inverse,
        t_q_step=t_q_step,
        t_primitive_exponent=t_primitive_exponent,
        base_q=base_q,
        base_primitive_exponent=base_primitive_exponent,
        primitive_support=primitive_support,
        normalized_support=normalized_support,
        quotient_word=quotient_word,
        normalized_word=normalized_word,
        product_matches=product_matches,
        forward_factor_law_ok=forward_factor_law_ok,
        inherited_product_rigidity_ok=inherited_product_rigidity_ok,
        next_debt=(
            "find a theorem-legal arithmetic producer for "
            "z^121*(1+z+z^2)*(1-z^263) with the forced C25 trace/KSY "
            "theta2 context; the finite product geometry is already rigid"
        ),
        row_ok=row_ok,
    )


def main() -> int:
    print("p25 Lane B Robert KSY Kubert-Lang primitive-D word gate")
    profile = profile_primitive_word()
    print(f"primitive_word_profile={profile}")
    print("coordinate_change")
    print(
        "  "
        f"D_q={profile.d_q_step} D_q_inverse={profile.d_q_inverse} "
        f"T_q={profile.t_q_step} T_as_D_power={profile.t_primitive_exponent}"
    )
    print(
        "  "
        f"base_q={profile.base_q} base_as_D_power={profile.base_primitive_exponent}"
    )
    print("primitive_support")
    print(f"  {profile.primitive_support}")
    print("normalized_support")
    print(f"  {profile.normalized_support}")
    print("product_matches")
    for match in profile.product_matches:
        print(f"  {match}")
    print("factor_laws")
    print("  KL packet = z^121 * (1 + z + z^2) * (1 - z^263)")
    print("  normalized packet = (1 + z + z^2) * (1 - z^263)")
    print("interpretation")
    print("  KL_graph_packet_is_the_existing_primitive_bridge_word=1")
    print("  existing_signed_2x3_product_rigidity_applies_to_the_KL_packet=1")
    print("  no_new_short_product_geometry_is_opened_by_the_Kubert_Lang_coordinate=1")
    print("  theorem_search_should_target_this_rigid_primitive_word_plus_K_trace=1")
    print(f"robert_ksy_theta2_kubert_lang_primitive_word_rows={int(profile.row_ok)}/1")
    print("conclusion=reported_p25_laneB_robert_ksy_theta2_kubert_lang_primitive_word_gate")
    return 0 if profile.row_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
