#!/usr/bin/env python3
"""Local C_169 nonsplitting obstruction for the p25 square-axis bridge.

The carry-cocycle gate shows that a split C_13 x C_13 no-carry lift is a false
friend: it keeps many finite invariants but fails the bridge trace.  This gate
records the local arithmetic reason.  The actual C-axis source is the cyclic
order-169 subgroup of F_677^* generated by p^2.  Its order-13 subgroup is the
kernel of projection to the visible C_13 quotient, and it has no complement.

Consequently every lift of a nonzero visible C_13 class has order 169 and a
nontrivial 13th power in the kernel.  The bridge's D and T C-multipliers live
in those nonsplit lifts; they cannot be replaced by independent order-13
fiber units without losing the cyclic carry law.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd

from p25_laneB_square_axis_bridge_factor_kummer_gate import factor_profile
from p25_laneB_square_axis_bridge_raw_source_gate import source_generators, square_axis_case
from p25_laneB_square_axis_bridge_raw_source_character_gate import BRIDGE_SHIFT, D_SHIFT


@dataclass(frozen=True)
class C169NonsplitProfile:
    c_modulus: int
    c_generator: int
    c_generator_order: int
    kernel_generator: int
    kernel_order: int
    kernel_exponents: tuple[int, ...]
    order13_exponents: tuple[int, ...]
    order13_low_residues: tuple[int, ...]
    nonzero_low_section_orders: tuple[tuple[int, tuple[int, ...]], ...]
    section_13th_power_exponents: tuple[tuple[int, int], ...]
    complement_exists: bool
    d_low: int
    d_multiplier: int
    d_section_orders: tuple[int, ...]
    d_13th_power_exponent: int
    d_13th_power_value: int
    t_low: int
    t_multiplier: int
    t_section_orders: tuple[int, ...]
    t_13th_power_exponent: int
    t_13th_power_value: int
    d_c169_min_degree: int
    t_c169_min_degree: int
    d_c13_min_degree: int
    t_c13_min_degree: int


def cyclic_order(exponent: int) -> int:
    if exponent % 169 == 0:
        return 1
    return 169 // gcd(169, exponent)


def section_exponents(low: int) -> tuple[int, ...]:
    return tuple(low + 13 * fiber for fiber in range(13))


def section_orders(low: int) -> tuple[int, ...]:
    return tuple(sorted({cyclic_order(exponent) for exponent in section_exponents(low)}))


def section_13th_power_exponent(low: int) -> int:
    return (13 * low) % 169


def profile_nonsplit() -> C169NonsplitProfile:
    case = square_axis_case()
    _right_generator, c_generator = source_generators(case)
    c_modulus = case.c_source.modulus
    kernel_generator = pow(c_generator, 13, c_modulus)
    kernel_exponents = tuple(range(0, 169, 13))
    order13_exponents = tuple(exponent for exponent in range(1, 169) if cyclic_order(exponent) == 13)
    order13_low_residues = tuple(sorted({exponent % 13 for exponent in order13_exponents}))
    nonzero_low_section_orders = tuple((low, section_orders(low)) for low in range(1, 13))
    section_13th_powers = tuple((low, section_13th_power_exponent(low)) for low in range(1, 13))
    complement_exists = any(
        any(cyclic_order(exponent) == 13 for exponent in section_exponents(low))
        for low in range(1, 13)
    )
    d_profile = factor_profile("D_segment", D_SHIFT)
    t_profile = factor_profile("bridge_edge", BRIDGE_SHIFT)
    d_low = D_SHIFT[1] % 13
    t_low = BRIDGE_SHIFT[1] % 13
    d_power_exponent = section_13th_power_exponent(d_low)
    t_power_exponent = section_13th_power_exponent(t_low)

    return C169NonsplitProfile(
        c_modulus=c_modulus,
        c_generator=c_generator,
        c_generator_order=cyclic_order(1),
        kernel_generator=kernel_generator,
        kernel_order=cyclic_order(13),
        kernel_exponents=kernel_exponents,
        order13_exponents=order13_exponents,
        order13_low_residues=order13_low_residues,
        nonzero_low_section_orders=nonzero_low_section_orders,
        section_13th_power_exponents=section_13th_powers,
        complement_exists=complement_exists,
        d_low=d_low,
        d_multiplier=d_profile.c_multiplier,
        d_section_orders=section_orders(d_low),
        d_13th_power_exponent=d_power_exponent,
        d_13th_power_value=pow(c_generator, d_power_exponent, c_modulus),
        t_low=t_low,
        t_multiplier=t_profile.c_multiplier,
        t_section_orders=section_orders(t_low),
        t_13th_power_exponent=t_power_exponent,
        t_13th_power_value=pow(c_generator, t_power_exponent, c_modulus),
        d_c169_min_degree=d_profile.c_c169_min_degree,
        t_c169_min_degree=t_profile.c_c169_min_degree,
        d_c13_min_degree=d_profile.c_c13_min_degree,
        t_c13_min_degree=t_profile.c_c13_min_degree,
    )


def main() -> int:
    print("p25 Lane B square-axis bridge C169 nonsplit gate")
    profile = profile_nonsplit()
    row_ok = (
        profile.c_modulus == 677
        and profile.c_generator == 354
        and profile.c_generator_order == 169
        and profile.kernel_generator == 246
        and profile.kernel_order == 13
        and profile.kernel_exponents == tuple(range(0, 169, 13))
        and profile.order13_exponents == tuple(range(13, 169, 13))
        and profile.order13_low_residues == (0,)
        and profile.nonzero_low_section_orders == tuple((low, (169,)) for low in range(1, 13))
        and profile.section_13th_power_exponents == tuple((low, 13 * low) for low in range(1, 13))
        and not profile.complement_exists
        and profile.d_low == 3
        and profile.d_multiplier == 85
        and profile.d_section_orders == (169,)
        and profile.d_13th_power_exponent == 39
        and profile.d_13th_power_value == 383
        and profile.t_low == 9
        and profile.t_multiplier == 667
        and profile.t_section_orders == (169,)
        and profile.t_13th_power_exponent == 117
        and profile.t_13th_power_value == 365
        and profile.d_c169_min_degree == 169
        and profile.t_c169_min_degree == 169
        and profile.d_c13_min_degree == 13
        and profile.t_c13_min_degree == 13
    )

    print(f"c169_nonsplit_profile={profile}")
    print("extension_laws")
    print("  C-source is <354 mod 677> of order 169")
    print("  kernel of C169 -> C13 is <354^13=246>, exponents 0,13,...,156")
    print("  all order-13 elements have exponent 0 mod 13 and project trivially")
    print("  every lift of a nonzero C13 class has order 169")
    print("  the 13th power of a lift with low class a is the kernel element g^(13a)")
    print("bridge_multiplier_laws")
    print("  D_c low class 3 has only order-169 lifts and 13th-power kernel exponent 39")
    print("  T_c low class 9 has only order-169 lifts and 13th-power kernel exponent 117")
    print("  visible C13 Kummer cost 13 is only the shadow; the C169 lift cost remains 169")
    print("interpretation")
    print("  local_C169_source_has_no_C13xC13_complement=1")
    print("  independent_order13_fiber_units_cannot_encode_the_bridge_carry=1")
    print("  arithmetic_realization_must_use_primitive_C169_source_units=1")
    print("  split_fiber_model_is_not_a_local_multiplicative_source=1")
    print(f"square_axis_bridge_c169_nonsplit_rows={int(row_ok)}/1")
    print("conclusion=reported_p25_laneB_square_axis_bridge_c169_nonsplit_gate")
    return 0 if row_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
