#!/usr/bin/env python3
"""Structured-basis audit for centered Cauchy-Binet noncancellation.

The centered marginal determinant has the exact form

    det(A B R^t)

where A and R are component-difference coefficient matrices and B is the
Hermitian trace form.  A tempting p-adic proof would find a natural integral
basis/filtration in which the exterior Cauchy-Binet expansion has a surviving
unit initial term and all other terms are forced into the maximal ideal.

This audit tests that idea in small actual-CM rows.  It deliberately restricts
to structured bases:

* the packet power basis;
* the first available Frobenius normal basis generated by a small power of X;
* the middle-Frobenius +/- eigenspace basis when the packet degree is even;
* a Hermitian Gram-Schmidt basis starting from the power basis.

These are not proof objects for p24, but they are the finite-field reductions
one would expect to expose a simple p-integral triangularization if it existed.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from itertools import combinations
from math import gcd

import sympy as sp
from cypari2 import Pari

from centered_marginal_cauchy_binet_audit import (
    column_submatrix,
    component_difference_vectors,
    det_mod,
    hermitian_power_basis_matrix,
    matmul_mod,
    submatrix,
    transpose,
)
from crt_partial_moment_projection_scan import coprime_components
from cycle_period_complexity_scan import find_full_cycle_prime
from hermitian_trace_gram_scan import frobenius_middle_vector, poly_pow_mod
from l1_axis_injectivity_scan import coeff_vector, discriminants, rank_mod_q
from packetized_relative_content_scan import packet_factors
from relative_moment_projection_scan import (
    find_splitting_primes,
    quotient_sizes_any,
    rotate,
    section_fiber_polynomials,
)

X = sp.symbols("X")


@dataclass(frozen=True)
class BasisAudit:
    name: str
    left_pluecker_nonzero: int
    right_pluecker_nonzero: int
    pluecker_total: int
    nonzero_b_on_support: int
    nonzero_terms: int
    diagonal_terms: int
    off_diagonal_terms: int
    degree_initial_term_count: int
    degree_initial_sum: int
    degree_initial_weight: int
    reverse_initial_term_count: int
    edge_initial_term_count: int
    center_initial_term_count: int
    higher_nonzero_terms: int
    cb_sum: int


@dataclass(frozen=True)
class FiltrationAudit:
    D: int
    q: int
    ell: int
    h: int
    m: int
    n: int
    factor_degree: int
    left: int
    right: int
    window_dim: int
    window_det: int
    basis_rows: tuple[BasisAudit, ...]


def matrix_from_columns(columns: list[list[int]]) -> list[list[int]]:
    if not columns:
        return []
    return [[column[row] for column in columns] for row in range(len(columns[0]))]


def inverse_matrix_mod(matrix: list[list[int]], q: int) -> list[list[int]] | None:
    try:
        inv = sp.Matrix(matrix).inv_mod(q)
    except Exception:
        return None
    return [[int(inv[row, col]) % q for col in range(inv.cols)] for row in range(inv.rows)]


def transform_rows(
    rows: list[list[int]],
    basis_inverse: list[list[int]],
    q: int,
) -> list[list[int]]:
    out: list[list[int]] = []
    for row in rows:
        out.append(
            [
                sum(basis_inverse[i][j] * row[j] for j in range(len(row))) % q
                for i in range(len(row))
            ]
        )
    return out


def transform_form(
    B: list[list[int]],
    basis_matrix: list[list[int]],
    q: int,
) -> list[list[int]]:
    return matmul_mod(matmul_mod(transpose(basis_matrix), B, q), basis_matrix, q)


def frobenius_power_vector(
    vector: list[int],
    factor: sp.Poly,
    q: int,
    power_index: int,
) -> list[int]:
    x_image = poly_pow_mod(sp.Poly(X, X, modulus=q), q**power_index, factor)
    total = sp.Poly(0, X, modulus=q)
    power = sp.Poly(1, X, modulus=q)
    for coeff in vector:
        if coeff:
            total = (total + coeff * power).rem(factor)
        power = (power * x_image).rem(factor)
    return coeff_vector(total.rem(factor), factor.degree(), q)


def normal_basis_matrix(factor: sp.Poly, q: int) -> tuple[str, list[list[int]]] | None:
    d = factor.degree()
    x_poly = sp.Poly(X, X, modulus=q)
    for exponent in range(1, 2 * d + 3):
        alpha = poly_pow_mod(x_poly, exponent, factor)
        alpha_vector = coeff_vector(alpha, d, q)
        columns = [
            frobenius_power_vector(alpha_vector, factor, q, i)
            for i in range(d)
        ]
        matrix = matrix_from_columns(columns)
        if rank_mod_q(transpose(columns), q) == d and inverse_matrix_mod(matrix, q):
            return f"normal_x^{exponent}", matrix
    return None


def kernel_basis_mod_q(matrix: list[list[int]], q: int) -> list[list[int]]:
    mat = [[value % q for value in row] for row in matrix]
    rows = len(mat)
    cols = len(mat[0]) if rows else 0
    rank = 0
    pivots: list[int] = []
    for col in range(cols):
        pivot = None
        for row in range(rank, rows):
            if mat[row][col] % q:
                pivot = row
                break
        if pivot is None:
            continue
        mat[rank], mat[pivot] = mat[pivot], mat[rank]
        inv = pow(mat[rank][col] % q, -1, q)
        mat[rank] = [(value * inv) % q for value in mat[rank]]
        for row in range(rows):
            if row == rank:
                continue
            scale = mat[row][col] % q
            if scale:
                mat[row] = [
                    (left - scale * right) % q
                    for left, right in zip(mat[row], mat[rank])
                ]
        pivots.append(col)
        rank += 1
        if rank == rows:
            break
    free_cols = [col for col in range(cols) if col not in pivots]
    basis: list[list[int]] = []
    for free in free_cols:
        vector = [0] * cols
        vector[free] = 1
        for row, pivot_col in enumerate(pivots):
            vector[pivot_col] = (-mat[row][free]) % q
        basis.append(vector)
    return basis


def middle_eigenbasis_matrix(factor: sp.Poly, q: int) -> list[list[int]] | None:
    d = factor.degree()
    if d % 2:
        return None
    standard = [[1 if i == j else 0 for i in range(d)] for j in range(d)]
    columns = [frobenius_middle_vector(vector, factor, q) for vector in standard]
    C = matrix_from_columns(columns)
    plus_rows = [
        [(C[row][col] - (1 if row == col else 0)) % q for col in range(d)]
        for row in range(d)
    ]
    minus_rows = [
        [(C[row][col] + (1 if row == col else 0)) % q for col in range(d)]
        for row in range(d)
    ]
    basis_columns = kernel_basis_mod_q(plus_rows, q) + kernel_basis_mod_q(minus_rows, q)
    if len(basis_columns) != d:
        return None
    matrix = matrix_from_columns(basis_columns)
    if inverse_matrix_mod(matrix, q) is None:
        return None
    return matrix


def hermitian_orthogonal_basis_matrix(B: list[list[int]], q: int) -> list[list[int]] | None:
    """Naive finite-field Gram-Schmidt for the Hermitian trace matrix."""

    d = len(B)
    basis: list[list[int]] = []

    def pair(left: list[int], right: list[int]) -> int:
        return sum(
            left[i] * B[i][j] * right[j]
            for i in range(d)
            for j in range(d)
        ) % q

    candidates = [[1 if i == j else 0 for i in range(d)] for j in range(d)]
    for candidate in candidates:
        vector = candidate[:]
        for old in basis:
            denom = pair(old, old)
            if not denom:
                continue
            scale = pair(old, vector) * pow(denom, -1, q) % q
            vector = [(value - scale * old_i) % q for value, old_i in zip(vector, old)]
        if any(vector) and pair(vector, vector):
            basis.append(vector)
        if len(basis) == d:
            matrix = matrix_from_columns(basis)
            if inverse_matrix_mod(matrix, q):
                return matrix
    return None


def basis_matrices(factor: sp.Poly, B: list[list[int]], q: int) -> list[tuple[str, list[list[int]]]]:
    d = factor.degree()
    out: list[tuple[str, list[list[int]]]] = [
        ("power", [[1 if i == j else 0 for j in range(d)] for i in range(d)])
    ]
    normal = normal_basis_matrix(factor, q)
    if normal is not None:
        out.append(normal)
    middle = middle_eigenbasis_matrix(factor, q)
    if middle is not None:
        out.append(("middle_frobenius_eigen", middle))
    orthogonal = hermitian_orthogonal_basis_matrix(B, q)
    if orthogonal is not None:
        out.append(("hermitian_orthogonal_power_gs", orthogonal))
    return out


def term_weight(S: tuple[int, ...], T: tuple[int, ...], weights: list[int]) -> int:
    return sum(weights[i] for i in S) + sum(weights[j] for j in T)


def basis_audit(
    name: str,
    basis_matrix: list[list[int]],
    left_vectors: list[list[int]],
    right_vectors: list[list[int]],
    B: list[list[int]],
    window_det: int,
    q: int,
) -> BasisAudit | None:
    d = len(B)
    r = len(left_vectors)
    basis_inverse = inverse_matrix_mod(basis_matrix, q)
    if basis_inverse is None:
        return None
    A = transform_rows(left_vectors, basis_inverse, q)
    R = transform_rows(right_vectors, basis_inverse, q)
    B_new = transform_form(B, basis_matrix, q)

    col_sets = tuple(combinations(range(d), r))
    left_dets = {
        cols: det_mod(column_submatrix(A, cols), q)
        for cols in col_sets
    }
    right_dets = {
        cols: det_mod(column_submatrix(R, cols), q)
        for cols in col_sets
    }
    left_support = [cols for cols, det in left_dets.items() if det]
    right_support = [cols for cols, det in right_dets.items() if det]

    degree_weights = list(range(d))
    reverse_weights = list(reversed(range(d)))
    edge_weights = [min(i, d - 1 - i) for i in range(d)]
    center_weights = [abs(2 * i - (d - 1)) for i in range(d)]

    cb_sum = 0
    nonzero_b = 0
    nonzero_terms = 0
    diagonal_terms = 0
    off_diagonal_terms = 0
    degree_min: int | None = None
    degree_initial_sum = 0
    degree_initial_count = 0
    reverse_weights_seen: list[int] = []
    edge_weights_seen: list[int] = []
    center_weights_seen: list[int] = []
    term_records: list[tuple[int, int]] = []

    for S in left_support:
        det_left = left_dets[S]
        for T in right_support:
            det_b = det_mod(submatrix(B_new, S, T), q)
            if det_b:
                nonzero_b += 1
            term = det_left * det_b * right_dets[T] % q
            if not term:
                continue
            nonzero_terms += 1
            if S == T:
                diagonal_terms += 1
            else:
                off_diagonal_terms += 1
            cb_sum = (cb_sum + term) % q
            degree_w = term_weight(S, T, degree_weights)
            reverse_weights_seen.append(term_weight(S, T, reverse_weights))
            edge_weights_seen.append(term_weight(S, T, edge_weights))
            center_weights_seen.append(term_weight(S, T, center_weights))
            term_records.append((degree_w, term))
            if degree_min is None or degree_w < degree_min:
                degree_min = degree_w
                degree_initial_sum = term
                degree_initial_count = 1
            elif degree_w == degree_min:
                degree_initial_sum = (degree_initial_sum + term) % q
                degree_initial_count += 1

    if cb_sum != window_det:
        raise AssertionError(f"Cauchy-Binet mismatch in basis {name}")
    if degree_min is None:
        degree_min = -1

    def initial_count(values: list[int]) -> int:
        if not values:
            return 0
        minimum = min(values)
        return sum(1 for value in values if value == minimum)

    higher_nonzero = sum(1 for weight, _ in term_records if weight != degree_min)
    return BasisAudit(
        name=name,
        left_pluecker_nonzero=len(left_support),
        right_pluecker_nonzero=len(right_support),
        pluecker_total=len(col_sets),
        nonzero_b_on_support=nonzero_b,
        nonzero_terms=nonzero_terms,
        diagonal_terms=diagonal_terms,
        off_diagonal_terms=off_diagonal_terms,
        degree_initial_term_count=degree_initial_count,
        degree_initial_sum=degree_initial_sum % q,
        degree_initial_weight=degree_min,
        reverse_initial_term_count=initial_count(reverse_weights_seen),
        edge_initial_term_count=initial_count(edge_weights_seen),
        center_initial_term_count=initial_count(center_weights_seen),
        higher_nonzero_terms=higher_nonzero,
        cb_sum=cb_sum,
    )


def audit_case(
    D: int,
    q: int,
    ell: int,
    cycle: list[int],
    m: int,
    factor: sp.Poly,
    left: int,
    right: int,
) -> FiltrationAudit | None:
    h = len(cycle)
    n = h // m
    d = factor.degree()
    if d % 2:
        return None
    if pow(q, d // 2, n) != n - 1:
        return None
    r = left - 1
    if right - 1 < r or d < r:
        return None

    fibers = section_fiber_polynomials(cycle, q, m, "complement")
    residues = [fiber.rem(factor) for fiber in fibers]
    left_vectors = component_difference_vectors(residues, left, q, factor)
    right_vectors_full = component_difference_vectors(residues, right, q, factor)
    right_vectors = right_vectors_full[:r]
    B = hermitian_power_basis_matrix(factor, q)
    window = matmul_mod(matmul_mod(left_vectors, B, q), transpose(right_vectors), q)
    window_det = det_mod(window, q)

    rows: list[BasisAudit] = []
    for name, matrix in basis_matrices(factor, B, q):
        row = basis_audit(name, matrix, left_vectors, right_vectors, B, window_det, q)
        if row is not None:
            rows.append(row)
    return FiltrationAudit(
        D=D,
        q=q,
        ell=ell,
        h=h,
        m=m,
        n=n,
        factor_degree=d,
        left=left,
        right=right,
        window_dim=r,
        window_det=window_det,
        basis_rows=tuple(rows),
    )


def scan(args: argparse.Namespace) -> FiltrationAudit | None:
    pari = Pari()
    pari.allocatemem(256 * 1024 * 1024)
    seen: set[int] = set()
    cases = 0
    for D in discriminants(args.max_abs_D, args.only_D):
        if D in seen:
            continue
        seen.add(D)
        try:
            hilbert = pari.polclass(D)
            h = int(pari.poldegree(hilbert))
        except Exception:
            continue
        if not (args.min_h <= h <= args.max_h):
            continue
        quotient_sizes = quotient_sizes_any(
            h,
            max_prime=args.max_prime_quotients,
            max_composite=args.max_composite_quotients,
            min_n=args.min_n,
            max_n=args.max_n,
        )
        quotient_sizes = [
            m
            for m in quotient_sizes
            if gcd(m, h // m) == 1
            and m <= args.max_m
            and (args.only_m is None or m == args.only_m)
            and len([c for c in coprime_components(m) if c > 2]) >= 2
        ]
        if not quotient_sizes:
            continue
        splits = find_splitting_primes(
            pari,
            hilbert,
            h,
            args.q_start,
            args.q_stop,
            args.max_splitting_primes,
        )
        case_had_cycle = False
        for q, roots in splits:
            full = find_full_cycle_prime(roots, D, q)
            if full is None:
                continue
            case_had_cycle = True
            ell, cycle = full
            shifted = rotate(cycle, args.origin_shift % h)
            for m in quotient_sizes:
                components = tuple(c for c in coprime_components(m) if c > 2)
                n = h // m
                for factor in packet_factors(n, q):
                    if factor.degree() == 1 and not args.include_linear:
                        continue
                    if factor.degree() > args.max_factor_degree:
                        continue
                    for left in components:
                        if args.only_left and left != args.only_left:
                            continue
                        for right in components:
                            if args.only_right and right != args.only_right:
                                continue
                            row = audit_case(D, q, ell, shifted, m, factor, left, right)
                            if row is not None:
                                return row
        if case_had_cycle:
            cases += 1
            if cases >= args.max_cases:
                break
    return None


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--max-cases", type=int, default=24)
    parser.add_argument("--min-h", type=int, default=12)
    parser.add_argument("--max-h", type=int, default=220)
    parser.add_argument("--max-abs-D", type=int, default=80000)
    parser.add_argument("--max-prime-quotients", type=int, default=12)
    parser.add_argument("--max-composite-quotients", type=int, default=24)
    parser.add_argument("--min-n", type=int, default=3)
    parser.add_argument("--max-n", type=int, default=220)
    parser.add_argument("--q-start", type=int, default=101)
    parser.add_argument("--q-stop", type=int, default=600000)
    parser.add_argument("--max-splitting-primes", type=int, default=2)
    parser.add_argument("--max-m", type=int, default=120)
    parser.add_argument("--max-factor-degree", type=int, default=12)
    parser.add_argument("--include-linear", action="store_true")
    parser.add_argument("--origin-shift", type=int, default=0)
    parser.add_argument("--only-D", type=int)
    parser.add_argument("--only-m", type=int)
    parser.add_argument("--only-left", type=int)
    parser.add_argument("--only-right", type=int)
    args = parser.parse_args()

    row = scan(args)
    if row is None:
        raise SystemExit("no eligible case found")
    print("Centered marginal p-adic filtration audit")
    print(f"D={row.D}")
    print(f"q={row.q}")
    print(f"ell={row.ell}")
    print(f"h={row.h}")
    print(f"m={row.m}")
    print(f"n={row.n}")
    print(f"factor_degree={row.factor_degree}")
    print(f"pair=({row.left},{row.right})")
    print(f"window_dim={row.window_dim}")
    print(f"window_det={row.window_det}")
    print()
    print("basis support")
    for basis in row.basis_rows:
        print(f"  basis={basis.name}")
        print(
            "    pluecker="
            f"{basis.left_pluecker_nonzero}/{basis.pluecker_total},"
            f"{basis.right_pluecker_nonzero}/{basis.pluecker_total}"
        )
        print(
            "    terms="
            f"nonzero={basis.nonzero_terms} diagonal={basis.diagonal_terms} "
            f"off_diagonal={basis.off_diagonal_terms} "
            f"B_on_support={basis.nonzero_b_on_support}"
        )
        print(
            "    initials="
            f"degree_count={basis.degree_initial_term_count} "
            f"degree_sum={basis.degree_initial_sum} "
            f"degree_weight={basis.degree_initial_weight} "
            f"reverse_count={basis.reverse_initial_term_count} "
            f"edge_count={basis.edge_initial_term_count} "
            f"center_count={basis.center_initial_term_count}"
        )
        print(
            "    degree_higher_nonzero_terms="
            f"{basis.higher_nonzero_terms}"
        )
    print()
    print("interpretation")
    print("  structured_basis_cauchy_binet_invariance_checked=1")
    print("  degree_initial_sum_equal_window_det_means_higher_layers_vanish_mod_q")
    print("  one_pluecker_support_would_indicate_visible_triangularization")
    print("conclusion=reported_centered_marginal_padic_filtration_audit")


if __name__ == "__main__":
    main()
