#!/usr/bin/env python3
"""Search composite split ideals for better p24 cycle quotients.

Earlier audits looked for a single split prime whose ideal class generated a
large subgroup of the smooth p24 class group.  But a product of several small
split prime ideals can have the same class as a large single prime while
having much smaller norm.  Such a composite ideal would define the same kind
of embedded split-cycle quotient, with `X0(N)` degree governed by the composite
norm N rather than by the largest single prime found so far.

This script computes discrete logs in the cyclic class group generated by the
prime above 23, then searches small signed squarefree products whose class has
index 314, 422, or 66254:

    gcd(h, log(product)) in {314, 422, 66254}.

The first two are the best small quotient sizes from the period-selector route.
The third is the balanced decomposed-CM quotient, whose recovery degree would
be only 3107441 if an embedded quotient were constructible.
The script is still only an audit: finding a better composite cycle does not
solve the seedless quotient-polynomial problem, but it can sharpen the formal
embedded candidate.
"""

from __future__ import annotations

import argparse
import itertools
import math
from dataclasses import dataclass

import sympy as sp
from cypari2 import Pari
from sympy.ntheory.modular import crt

P24 = 10**24 + 7
D_K = -652834595820939249713143
CLASS_NUMBER = 205880396014
GENERATOR_PRIME = 23
CLASS_FACTORS = (2, 157, 211, 3107441)
TARGET_INDICES = (314, 422, 66254)


@dataclass(frozen=True)
class PrimeLog:
    ell: int
    log: int
    order: int
    index: int


@dataclass(frozen=True)
class ProductHit:
    norm: int
    index: int
    order: int
    log: int
    signed_primes: tuple[int, ...]


def form_key(pari: Pari, form) -> str:
    return str(pari.qfbred(form))


def inverse_form(pari: Pari, form):
    return pari(f"Qfb({int(form[0])},{-int(form[1])},{int(form[2])})")


def compose(pari: Pari, a, b, nucomp_l: int):
    return pari.qfbred(pari.qfbnucomp(a, b, nucomp_l))


def pow_form(pari: Pari, form, exponent: int, nucomp_l: int):
    return pari.qfbred(pari.qfbnupow(form, int(exponent), nucomp_l))


def bsgs_prime_order_log(pari: Pari, base, target, order: int, nucomp_l: int) -> int:
    """Solve base^x=target in a cyclic group of prime order."""
    if order == 2:
        return 0 if form_key(pari, target) == form_key(pari, pow_form(pari, base, 0, nucomp_l)) else 1
    m = math.isqrt(order) + 1
    table: dict[str, int] = {}
    current = pow_form(pari, base, 0, nucomp_l)
    for j in range(m):
        table.setdefault(form_key(pari, current), j)
        current = compose(pari, current, base, nucomp_l)

    step = inverse_form(pari, pow_form(pari, base, m, nucomp_l))
    gamma = target
    for i in range(m + 1):
        key = form_key(pari, gamma)
        if key in table:
            value = i * m + table[key]
            if value < order:
                return value
        gamma = compose(pari, gamma, step, nucomp_l)
    raise RuntimeError(f"discrete log failed for order {order}")


def class_log(pari: Pari, generator, form, nucomp_l: int) -> int:
    residues: list[int] = []
    moduli: list[int] = []
    for q in CLASS_FACTORS:
        base_q = pow_form(pari, generator, CLASS_NUMBER // q, nucomp_l)
        target_q = pow_form(pari, form, CLASS_NUMBER // q, nucomp_l)
        residues.append(bsgs_prime_order_log(pari, base_q, target_q, q, nucomp_l))
        moduli.append(q)
    value, modulus = crt(moduli, residues)
    if int(modulus) != CLASS_NUMBER:
        raise AssertionError((modulus, CLASS_NUMBER))
    return int(value) % CLASS_NUMBER


def split_prime_logs(prime_bound: int) -> list[PrimeLog]:
    pari = Pari()
    pari.allocatemem(512 * 1024 * 1024)
    nucomp_l = int((abs(D_K) // 4) ** 0.25) + 1
    generator = pari.qfbprimeform(D_K, GENERATOR_PRIME)
    rows: list[PrimeLog] = []
    for ell in sp.primerange(2, prime_bound + 1):
        if ell == GENERATOR_PRIME or sp.kronecker_symbol(D_K, ell) != 1:
            continue
        form = pari.qfbprimeform(D_K, int(ell))
        log_value = class_log(pari, generator, form, nucomp_l)
        index = math.gcd(CLASS_NUMBER, log_value)
        rows.append(PrimeLog(int(ell), log_value, CLASS_NUMBER // index, index))
    rows.append(PrimeLog(GENERATOR_PRIME, 1, CLASS_NUMBER, 1))
    return sorted(rows, key=lambda row: row.ell)


def search_products(rows: list[PrimeLog], max_factors: int, max_norm: int) -> list[ProductHit]:
    signed = [(row.ell, row.log % CLASS_NUMBER) for row in rows] + [
        (row.ell, (-row.log) % CLASS_NUMBER) for row in rows
    ]
    best: dict[tuple[int, tuple[int, ...]], ProductHit] = {}
    hits: list[ProductHit] = []

    for size in range(1, max_factors + 1):
        for combo in itertools.combinations(signed, size):
            abs_primes = tuple(sorted(abs(ell) for ell, _log in combo))
            if len(set(abs_primes)) != len(abs_primes):
                continue
            norm = math.prod(abs_primes)
            if norm > max_norm:
                continue
            log_sum = sum(log for _ell, log in combo) % CLASS_NUMBER
            index = math.gcd(CLASS_NUMBER, log_sum)
            if index not in TARGET_INDICES:
                continue
            signed_primes = tuple(ell if log == next(row.log for row in rows if row.ell == ell) % CLASS_NUMBER else -ell for ell, log in combo)
            hit = ProductHit(norm, index, CLASS_NUMBER // index, log_sum, signed_primes)
            key = (index, abs_primes)
            if key not in best or norm < best[key].norm:
                best[key] = hit
                hits.append(hit)
    return sorted(hits, key=lambda hit: (hit.index, hit.norm, len(hit.signed_primes)))


def exhaustive_norm_search(rows: list[PrimeLog], norm_bound: int) -> list[ProductHit]:
    """Enumerate all signed products of split prime powers up to norm_bound."""
    eligible = [row for row in rows if row.ell <= norm_bound]
    hits: list[ProductHit] = []

    def rec(start: int, norm: int, log_sum: int, terms: list[int]) -> None:
        if terms:
            index = math.gcd(CLASS_NUMBER, log_sum % CLASS_NUMBER)
            if index in TARGET_INDICES:
                hits.append(
                    ProductHit(
                        norm=norm,
                        index=index,
                        order=CLASS_NUMBER // index,
                        log=log_sum % CLASS_NUMBER,
                        signed_primes=tuple(terms),
                    )
                )
        for pos in range(start, len(eligible)):
            row = eligible[pos]
            power = row.ell
            exponent = 1
            while norm * power <= norm_bound:
                for sign in (1, -1):
                    term = sign * (row.ell if exponent == 1 else row.ell**exponent)
                    rec(
                        pos + 1,
                        norm * power,
                        (log_sum + sign * exponent * row.log) % CLASS_NUMBER,
                        terms + [term],
                    )
                exponent += 1
                power *= row.ell

    rec(0, 1, 0, [])
    return sorted(hits, key=lambda hit: (hit.index, hit.norm, len(hit.signed_primes)))


def x0_index_for_squarefree(norm: int) -> int:
    value = norm
    for prime in sp.factorint(norm):
        value *= prime + 1
        value //= prime
    return value


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prime-bound", type=int, default=2000)
    ap.add_argument("--max-factors", type=int, default=3)
    ap.add_argument("--max-norm", type=int, default=10**9)
    ap.add_argument("--exhaustive-norm", type=int, default=10_000)
    ap.add_argument("--show", type=int, default=12)
    args = ap.parse_args()

    rows = split_prime_logs(args.prime_bound)
    sqrt_p = math.isqrt(P24)
    print("p24 composite split-cycle audit")
    print(f"p={P24}")
    print(f"D_K={D_K}")
    print(f"class_number={CLASS_NUMBER}")
    print(f"class_number_factorization={sp.factorint(CLASS_NUMBER)}")
    print(f"generator_prime={GENERATOR_PRIME}")
    print(f"prime_bound={args.prime_bound}")
    print(f"split_prime_logs={len(rows)}")
    print(f"max_factors={args.max_factors}")
    print(f"max_norm={args.max_norm}")
    print(f"exhaustive_norm={args.exhaustive_norm}")
    print()

    print("single_prime_reference")
    for row in rows:
        if row.ell in {2, 23, 677, 7349, 2897, 14057}:
            print(
                f"  ell={row.ell:6d} log={row.log:15d} "
                f"index={row.index:8d} order={row.order:12d}"
            )
    print()

    hits = search_products(rows, args.max_factors, args.max_norm)
    for index in TARGET_INDICES:
        selected = [hit for hit in hits if hit.index == index]
        print(f"best_composite_products_for_index_{index}")
        print("  norm x0_index order norm_over_sqrt x0_index_over_sqrt signed_primes log")
        for hit in selected[: args.show]:
            x0_index = x0_index_for_squarefree(hit.norm)
            print(
                f"  {hit.norm:12d} {x0_index:12d} {hit.order:12d} "
                f"{hit.norm / sqrt_p:14.6e} {x0_index / sqrt_p:18.6e} "
                f"{hit.signed_primes!s:28s} {hit.log}"
            )
        if not selected:
            print("  none")
        print()

    if args.exhaustive_norm:
        exhaustive = exhaustive_norm_search(rows, args.exhaustive_norm)
        print(f"exhaustive_signed_prime_power_products_norm_le_{args.exhaustive_norm}")
        for index in TARGET_INDICES:
            selected = [hit for hit in exhaustive if hit.index == index]
            print(f"  index_{index}")
            for hit in selected[: min(args.show, 8)]:
                print(
                    f"    norm={hit.norm:8d} order={hit.order:12d} "
                    f"signed_prime_powers={hit.signed_primes!s:24s} log={hit.log}"
                )
            if not selected:
                print("    none")
        print()

    print("interpretation")
    print("  composite_ideal_can_improve_the_formal_X0_degree_if_norm_below_single_prime=1")
    print("  this_does_not_solve_seedless_period_polynomial_construction=1")
    print("  target_index_314_corresponds_to_cycle_length_655670051=1")
    print("  target_index_422_corresponds_to_cycle_length_487868237=1")
    print("  target_index_66254_corresponds_to_cycle_length_3107441=1")
    print("conclusion=reported_composite_split_cycle_candidates")


if __name__ == "__main__":
    main()
