#!/usr/bin/env python3
"""Group-algebra bookkeeping for split-cycle period projectors.

This is the algebra behind the latest order-19 probe.  In the first strict
p24 trace the split prime above 2 appears to generate the class torsor, while
the split prime 19 generates the subgroup H whose cosets are the desired
quotient components.  The component sum is the subgroup idempotent

    e_H = sum_{k=0}^{n-1} g^{m k},  h = m n.

Low-level Hecke correspondences can move/orient components, but the period
itself is still this idempotent applied to the j-vector.  In the group algebra
of a cyclic torsor, any exact linear projector has support n.  If generated by
an unoriented 19-isogeny adjacency inside H, the required walk radius is at
least (n-1)/2.

The script records these lower bounds for the order-19 toy target and the
third-trace composite certificate target.
"""

from __future__ import annotations

import math
from dataclasses import dataclass


P = 10**24 + 7
SQRT_P = math.isqrt(P)


@dataclass(frozen=True)
class Target:
    name: str
    h: int
    quotient: int
    recovery: int
    oriented_edge_degree_proxy: int


TARGETS = (
    Target(
        name="first_trace_order19_with_split2_mover",
        h=278733727154,
        quotient=19,
        recovery=14670196166,
        oriented_edge_degree_proxy=3,
    ),
    Target(
        name="third_trace_composite_2_463_223inv",
        h=205880396014,
        quotient=66254,
        recovery=3107441,
        oriented_edge_degree_proxy=311808,
    ),
)


def main() -> None:
    print("Hecke projector barrier audit")
    print(f"p={P}")
    print(f"sqrt_floor={SQRT_P}")
    print()

    for target in TARGETS:
        if target.h != target.quotient * target.recovery:
            raise AssertionError(target)
        support = target.recovery
        unoriented_radius = (support - 1 + 1) // 2
        linear_projector_seeded_proxy = target.oriented_edge_degree_proxy * support
        unoriented_walk_proxy = target.oriented_edge_degree_proxy * unoriented_radius

        print(f"target={target.name}")
        print(f"  h={target.h}")
        print(f"  quotient_m={target.quotient}")
        print(f"  recovery_n=|H|={target.recovery}")
        print("  subgroup_projector=e_H=sum_{k=0}^{n-1} g^{m*k}")
        print(f"  exact_linear_projector_support_terms={support}")
        print(f"  exact_linear_projector_support_over_sqrt={support / SQRT_P:.6e}")
        print(f"  min_unoriented_radius_inside_H={unoriented_radius}")
        print(f"  min_unoriented_radius_over_sqrt={unoriented_radius / SQRT_P:.6e}")
        print(f"  edge_degree_proxy={target.oriented_edge_degree_proxy}")
        print(f"  support_times_edge_degree_proxy={linear_projector_seeded_proxy}")
        print(f"  support_times_edge_degree_over_sqrt={linear_projector_seeded_proxy / SQRT_P:.6e}")
        print(f"  radius_times_edge_degree_proxy={unoriented_walk_proxy}")
        print(f"  radius_times_edge_degree_over_sqrt={unoriented_walk_proxy / SQRT_P:.6e}")
        print()

    print("interpretation")
    print("  component_movers_orient_cosets_but_do_not_apply_e_H=1")
    print("  bounded_depth_local_Hecke_words_have_bounded_group_algebra_support=1")
    print("  exact_component_sum_requires_support_equal_to_recovery_degree=1")
    print("  escaping_this_bound_requires_nonlocal_high_order_trace_formula=1")
    print(
        "conclusion=small_correspondence_orientation_is_not_the_missing_"
        "embedded_period_projector"
    )


if __name__ == "__main__":
    main()
