#!/usr/bin/env python3
"""Near-square inverse-MITM scaling audit.

The inverse-tree machinery can enumerate all valid x0 values once A is fixed.
A possible asymptotic hope is meet-in-the-middle: rank A by a half-depth inverse
tree, then search only high-mass A values.

This exact small-field audit asks whether that ranking changes the exponent in
the family p = n^2 + 7.  For each calibration prime it computes, for every
nonsingular Montgomery A:

* inverse-tree mass at a shallow/half depth;
* whether a full strict DANGER x-only hit exists;
* how concentrated the full hits are in the mass-ranked A list; and
* the total inverse states generated by ranking all A.

If MITM were an exponent-changing selector, full hits should concentrate in a
vanishing prefix.  Constant lifts and O(p) ranking work instead mean the
method is useful after choosing A, but does not beat target-trace entropy.
"""

from __future__ import annotations

import argparse
from collections import Counter
from math import isqrt

from inverse_mass_correlation_probe import inverse_tree_size
from low_degree_character_trace_scan import prime_rows


def verifier_k(p: int) -> int:
    q = isqrt(p)
    return (q + 1 + isqrt(4 * q)).bit_length()


def inverse_tree_sizes_by_level(p: int, A: int, max_depth: int) -> tuple[list[int], int]:
    """Return final-level sizes 0..max_depth and total states seen.

    This wraps inverse_tree_size for clarity rather than speed; the audit keeps
    p small enough that exactness is more valuable than clever caching.
    """
    sizes = []
    states_seen = 0
    for depth in range(max_depth + 1):
        size = inverse_tree_size(p, A, depth)
        sizes.append(size)
        states_seen += size
    return sizes, states_seen


def summarize_prefixes(rows: list[tuple[int, bool, int]], prefix_fracs: tuple[float, ...]) -> list[str]:
    total = len(rows)
    hits = sum(1 for _, full, _ in rows if full)
    base = hits / total if total else 0.0
    out: list[str] = []
    for frac in prefix_fracs:
        n = max(1, int(total * frac))
        prefix = rows[:n]
        prefix_hits = sum(1 for _, full, _ in prefix if full)
        rate = prefix_hits / n
        lift = rate / base if base else 0.0
        capture = prefix_hits / hits if hits else 0.0
        out.append(
            f"prefix={frac:.3f} n={n} hits={prefix_hits} "
            f"rate={rate:.6f} lift={lift:.3f} capture={capture:.3f}"
        )
    return out


def audit_row(n: int, p: int, rank_depth: int | None, prefix_fracs: tuple[float, ...]) -> None:
    k = verifier_k(p)
    full_depth = k - 1
    rank = rank_depth if rank_depth is not None else max(1, full_depth // 2)
    max_depth = max(rank, full_depth)
    rows: list[tuple[int, bool, int]] = []
    total_rank_states = 0
    total_full_states = 0
    mass_hist = Counter()
    full_by_mass = Counter()

    for A in range(p):
        if (A * A - 4) % p == 0:
            continue
        sizes, states_seen = inverse_tree_sizes_by_level(p, A, max_depth)
        rank_mass = sizes[rank]
        full_mass = sizes[full_depth]
        full_hit = full_mass > 0
        total_rank_states += sum(sizes[: rank + 1])
        total_full_states += states_seen
        mass_hist[rank_mass] += 1
        if full_hit:
            full_by_mass[rank_mass] += 1
        rows.append((rank_mass, full_hit, A))

    rows.sort(key=lambda row: (row[0], -row[2]), reverse=True)
    total_A = len(rows)
    hits = sum(1 for _, full, _ in rows if full)
    base = hits / total_A if total_A else 0.0
    max_mass = rows[0][0] if rows else 0
    max_mass_A = sum(1 for mass, _, _ in rows if mass == max_mass)
    max_mass_hits = sum(1 for mass, full, _ in rows if mass == max_mass and full)
    top_masses = ",".join(
        f"{mass}:{mass_hist[mass]}({full_by_mass[mass]})"
        for mass in sorted(mass_hist, reverse=True)[:8]
    )

    print(
        f"row n={n} p={p} k={k} rank_depth={rank} full_depth={full_depth} "
        f"A={total_A} full_hits={hits} base={base:.6f}"
    )
    print(
        f"  total_rank_states={total_rank_states} "
        f"rank_states_per_A={total_rank_states / total_A:.3f} "
        f"rank_states_over_p={total_rank_states / p:.3f}"
    )
    print(
        f"  total_full_states={total_full_states} "
        f"full_states_per_A={total_full_states / total_A:.3f} "
        f"full_states_over_p={total_full_states / p:.3f}"
    )
    print(
        f"  max_rank_mass={max_mass} A_at_max_mass={max_mass_A} "
        f"full_hits_at_max_mass={max_mass_hits}"
    )
    print(f"  mass_hist_top=mass:A_count(full_hits) {top_masses}")
    for line in summarize_prefixes(rows, prefix_fracs):
        print(f"  {line}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--min-p", type=int, default=2_000)
    ap.add_argument("--max-p", type=int, default=50_000)
    ap.add_argument("--max-rows", type=int, default=6)
    ap.add_argument("--n-modulus", type=int, default=8)
    ap.add_argument("--n-residue", type=int, default=0)
    ap.add_argument("--rank-depth", type=int, default=0)
    ap.add_argument("--prefix-fracs", type=float, nargs="+", default=[0.005, 0.01, 0.02, 0.05, 0.10, 0.25])
    args = ap.parse_args()

    rows = prime_rows(args.min_p, args.max_p, args.max_rows, args.n_modulus, args.n_residue)
    print("inverse MITM near-square scaling audit")
    print("family=p=n^2+7")
    print(f"min_p={args.min_p}")
    print(f"max_p={args.max_p}")
    print(f"rows={len(rows)}")
    print(f"n_modulus={args.n_modulus}")
    print(f"n_residue={args.n_residue}")
    print(f"rank_depth_override={args.rank_depth or 'half'}")
    for n, p in rows:
        audit_row(n, p, args.rank_depth or None, tuple(args.prefix_fracs))
    print("conclusion=inverse_mitm_mass_is_constant_factor_ranking_not_subsqrt_A_selector")


if __name__ == "__main__":
    main()
