#!/usr/bin/env python3
"""Degree audit for seedless isogeny-cycle equations in the smooth p24 lead.

The third strict trace has a cyclic class group

    h = 2 * 157 * 211 * 3107441

and a very small split prime, ell=23, whose ideal class generates it.  This
looks tempting: perhaps a seedless "closed 23-isogeny cycle" or a quotient
cycle could define a target j-root without constructing H_D.

This script records the degree shape of that idea.  It intentionally does not
build any modular polynomials.  For a seedless condition coming from an
endomorphism of norm ell^r, the relevant X0 degree is

    psi(ell^r) = ell^r + ell^(r-1).

Thus log10(degree) is about r*log10(ell).  The p24 cycle lengths are class
group orders, so the seedless resultant is astronomically larger than the
sqrt(p)-scale problem.  The decomposed-CM split only becomes small after an
embedded CM root set, orbit, or equivalent quotient invariant is already known.
"""

from __future__ import annotations

from dataclasses import dataclass
import math

P24 = 10**24 + 7
SQRT_P = math.isqrt(P24)
TRACE = -1178414874616
D_K = -652834595820939249713143
CLASS_NUMBER = 205880396014
CLASS_FACTORS = [2, 157, 211, 3107441]

# Rows observed by smooth_class_tower_probe.py for the third target.
# "order" is the order of the split-prime ideal class; "index" is h/order.
OBSERVED_SPLIT_ACTIONS = [
    (23, 1, 205880396014),
    (2, 2, 102940198007),
    (2897, 157, 1311340102),
    (14057, 211, 975736474),
    (677, 314, 655670051),
    (7349, 422, 487868237),
]


@dataclass(frozen=True)
class CycleDegree:
    label: str
    ell: int
    cycle_order: int
    subgroup_index: int | None = None

    @property
    def log10_x0_degree(self) -> float:
        # psi(ell^r) = ell^r * (1 + 1/ell).
        return self.cycle_order * math.log10(self.ell) + math.log10(1 + 1 / self.ell)

    @property
    def log10_vs_sqrt_p(self) -> float:
        return self.log10_x0_degree - math.log10(SQRT_P)


def fmt_log10(value: float) -> str:
    if value < 100:
        return f"{value:.6f}"
    return f"{value:.6e}"


def print_p24_seedless_cycles() -> None:
    print("p24 seedless isogeny-cycle degree audit")
    print(f"p={P24}")
    print(f"sqrt_floor_p={SQRT_P}")
    print(f"trace={TRACE}")
    print(f"fundamental_D_K={D_K}")
    print(f"class_number={CLASS_NUMBER}")
    print(f"class_factors={CLASS_FACTORS}")
    print()

    print("observed_split_prime_actions")
    print("  ell index class_order factor_order")
    for ell, index, order in OBSERVED_SPLIT_ACTIONS:
        print(f"  {ell:5d} {index:8d} {order:12d} {factor_string(order)}")
    print()

    rows = [
        CycleDegree("full_23_generator_cycle", 23, CLASS_NUMBER, 1),
        CycleDegree("index_157_subgroup_cycle", 2897, CLASS_NUMBER // 157, 157),
        CycleDegree("index_211_subgroup_cycle", 14057, CLASS_NUMBER // 211, 211),
        CycleDegree("index_314_subgroup_cycle", 677, CLASS_NUMBER // 314, 314),
        CycleDegree("index_422_subgroup_cycle", 7349, CLASS_NUMBER // 422, 422),
    ]

    print("seedless_closed_cycle_degree_proxy")
    print("  label ell cycle_order index log10_psi(ell^order) log10_over_sqrt_p")
    for row in rows:
        print(
            f"  {row.label:30s} {row.ell:5d} {row.cycle_order:12d} "
            f"{row.subgroup_index or 0:8d} {fmt_log10(row.log10_x0_degree):>22s} "
            f"{fmt_log10(row.log10_vs_sqrt_p):>18s}"
        )
    print()

    best_factor_a = 2 * 157 * 211
    best_factor_b = 3107441
    print("best_decomposed_cm_shape_if_embedded_invariants_are_known")
    print(f"  h={CLASS_NUMBER}={best_factor_a}*{best_factor_b}")
    print(f"  quotient_degree={best_factor_a}")
    print(f"  recovery_degree={best_factor_b}")
    print(f"  largest_final_root_degree_over_sqrt_p={best_factor_b / SQRT_P:.6e}")
    print()

    lower_log = best_factor_b * math.log10(2)
    print("seedless_subgroup_generator_lower_bound")
    print("  If a subgroup of order 3107441 were generated by any prime-level")
    print("  correspondence at all, ell>=2, so the closed-cycle X0 degree has")
    print(f"  log10(degree) >= {fmt_log10(lower_log)} before it selects a CM root.")
    print(f"  That lower bound is still {fmt_log10(lower_log - math.log10(SQRT_P))} log10-units above sqrt(p).")
    print()


def print_toy_calibration_degree_context() -> None:
    toy_ell = 3
    toy_h = 30
    toy_log = toy_h * math.log10(toy_ell) + math.log10(1 + 1 / toy_ell)
    toy_degree = toy_ell**toy_h + toy_ell ** (toy_h - 1)
    print("toy_model_context_from_embedded_decomposition_calibration")
    print("  D=-5000, h=30, q=1259, ell=3 generator")
    print(f"  seedless_Phi_(3^30)_fixed_point_degree={toy_degree}")
    print(f"  seedless_log10_degree={toy_log:.6f}")
    print("  embedded_H_D_degree=30")
    print("  decomposed_after_embedded_cycle_degrees=6_and_5")
    print("  interpretation=seedless_cycle_resultant_is_not_the_decomposed_CM_saving")
    print()


def factor_string(n: int) -> str:
    factors: list[str] = []
    m = n
    d = 2
    while d * d <= m:
        exp = 0
        while m % d == 0:
            m //= d
            exp += 1
        if exp == 1:
            factors.append(str(d))
        elif exp:
            factors.append(f"{d}^{exp}")
        d += 1 if d == 2 else 2
    if m > 1:
        factors.append(str(m))
    return "*".join(factors) if factors else "1"


def main() -> None:
    print_p24_seedless_cycles()
    print_toy_calibration_degree_context()
    print("obstruction_summary")
    print("  seedless_full_modular_cycle_degree_is_exponential_in_class_order=1")
    print("  quotient_orbit_sums_are_small_only_after_embedded_roots_or_equivalent_invariants=1")
    print("  small_split_prime_generators_describe_class_action_but_not_a_seed_root=1")
    print("  constructing_horizontal_only_correspondence_requires_the_CM_order_filter=1")
    print(
        "conclusion=seedless_23_cycle_or_seedless_quotient_cycle_does_not_"
        "beat_sqrt_scale_for_the_strict_p24_certificate"
    )


if __name__ == "__main__":
    main()
