#!/usr/bin/env python3
"""Audit small imaginary CM factors inside the p24 target genus data.

The target discriminants contain small negative prime-discriminant factors:
`-7`, `-211`, and `-599`, plus products with the positive factor `4973929`.
These are tempting because a small CM field can be constructed cheaply if the
prime is principal in its ring class field.

This script distinguishes three facts:

* quadratic splitting, `Kronecker(D,p)=1`, which is only genus information;
* a principal norm equation `t^2 + |D| f^2 = 4p`, which gives an actual CM
  trace over F_p for discriminant D;
* the 2-adic depth of the resulting curve/twist order.

For p24, only the known `D=-7` near-square field is principal, and it has
depth 3.  The other small imaginary genus factors split but do not produce an
F_p CM trace.
"""

from __future__ import annotations

import math

import sympy as sp

P24 = 10**24 + 7
K = 40

# Negative fundamental discriminants generated by the small p24 genus factors.
CANDIDATE_D = (
    -7,
    -211,
    -599,
    -7 * 4973929,
    -211 * 4973929,
)


def v2(n: int) -> int:
    return (n & -n).bit_length() - 1


def cornacchia_prime(p: int, d: int) -> list[tuple[int, int]]:
    """Solutions to x^2 + d*y^2 = p for odd prime p."""
    if sp.kronecker_symbol(-d, p) != 1:
        return []
    solutions: set[tuple[int, int]] = set()
    for root in sp.sqrt_mod(-d, p, all_roots=True):
        a, b = p, min(int(root), p - int(root))
        while b * b > p:
            a, b = b, a % b
        x = abs(b)
        rem = p - x * x
        if rem >= 0 and rem % d == 0:
            y2 = rem // d
            y = math.isqrt(y2)
            if y * y == y2:
                solutions.add((x, y))
    return sorted(solutions)


def cornacchia_odd_conductor(p: int, d: int) -> list[tuple[int, int]]:
    """Odd-f solutions to t^2 + d*f^2 = 4p.

    If f is odd, f is invertible modulo 4p and t/f is a square root of -d
    modulo 4p.  Even-f solutions are handled by cornacchia_prime.
    """
    if sp.kronecker_symbol(-d, p) != 1:
        return []
    modulus = 4 * p
    roots: set[int] = set()
    for root_p in sp.sqrt_mod(-d, p, all_roots=True):
        for root_4 in (1, 3):  # d == 3 mod 4 for these candidates, so -d == 1 mod 4.
            root, _mod = sp.ntheory.modular.crt([p, 4], [int(root_p), root_4])
            root = int(root % modulus)
            roots.add(min(root, modulus - root))

    solutions: set[tuple[int, int]] = set()
    for root in roots:
        a, b = modulus, root
        while b * b > modulus:
            a, b = b, a % b
        t = abs(b)
        rem = modulus - t * t
        if rem >= 0 and rem % d == 0:
            f2 = rem // d
            f = math.isqrt(f2)
            if f * f == f2 and f % 2 == 1 and t % 2 == 1:
                solutions.add((t, f))
    return sorted(solutions)


def principal_traces(D: int) -> list[tuple[int, int]]:
    d = abs(D)
    traces: set[tuple[int, int]] = set()

    # Even conductor f=2y gives p=x^2+d*y^2 and trace t=2x.
    for x, y in cornacchia_prime(P24, d):
        traces.add((2 * x, 2 * y))

    # Odd conductor f gives the full 4p equation directly.
    for t, f in cornacchia_odd_conductor(P24, d):
        traces.add((t, f))

    return sorted(traces)


def main() -> None:
    print("p24 small genus CM factor audit")
    print(f"p={P24}")
    print(f"k={K}")
    print("D kronecker_split principal_trace_count traces")
    for D in CANDIDATE_D:
        split = sp.kronecker_symbol(D, P24)
        traces = principal_traces(D)
        print(f"D={D}")
        print(f"  kronecker_split={split}")
        print(f"  principal_trace_count={len(traces)}")
        if not traces:
            print("  traces=[]")
        for t, f in traces:
            rows = []
            for trace in (t, -t) if t else (0,):
                rows.append(
                    {
                        "trace": trace,
                        "conductor": f,
                        "v2_order": v2(P24 + 1 - trace),
                        "v2_twist": v2(P24 + 1 + trace),
                        "strict_hit": max(v2(P24 + 1 - trace), v2(P24 + 1 + trace)) >= K,
                    }
                )
            print(f"  traces={rows}")
    print(
        "conclusion=small_imaginary_genus_factors_are_either_nonprincipal_over_Fp_"
        "or_the_known_D_minus_7_depth3_curve;_no_strict_CM_shortcut"
    )


if __name__ == "__main__":
    main()
