#!/usr/bin/env python3
"""Small embedded decomposed-CM calibration.

This is a toy model for the p24 smooth-class lead.  It uses the ring class
discriminant D=-5000, whose class group is cyclic of order 30 and generated by
a norm-3 ideal.  Over q=1259 the Hilbert class polynomial splits completely.

The script explicitly:

1. computes H_D and its roots modulo q;
2. builds the horizontal 3-isogeny graph among those roots with Phi_3;
3. walks the resulting 30-cycle from a seed root;
4. constructs a decomposed embedded invariant by taking sums over cosets of a
   subgroup of size 5, yielding degrees 6 and 5 instead of degree 30.

The point is not that this is hard at D=-5000.  The point is to make the p24
missing primitive concrete: the decomposed polynomials are easy once the
embedded CM root set / class-action cycle is available, but this construction
uses a seed root and actual j-roots, not just an abstract class group.
"""

from __future__ import annotations

from dataclasses import dataclass

from cypari2 import Pari

D = -5000
Q = 1259
ELL = 3
H = 30
SUBGROUP_SIZE = 5
QUOTIENT_SIZE = H // SUBGROUP_SIZE


@dataclass(frozen=True)
class Decomposition:
    cycle: list[int]
    coset_sums: list[int]
    V: list[int]
    selected_y: int
    U: list[int]
    selected_roots: list[int]


def poly_mul_linear(poly: list[int], root: int, q: int) -> list[int]:
    """Multiply ascending-coefficient poly by (x-root) over F_q."""
    out = [0] * (len(poly) + 1)
    for i, coeff in enumerate(poly):
        out[i] = (out[i] - coeff * root) % q
        out[i + 1] = (out[i + 1] + coeff) % q
    return out


def monic_poly_from_roots(roots: list[int], q: int) -> list[int]:
    poly = [1]
    for root in roots:
        poly = poly_mul_linear(poly, root, q)
    return poly


def pari_linear_roots(poly, q: int) -> list[int]:
    pari = Pari()
    fac = pari(f"factor(Mod(1,{q})*({poly}))")
    roots: list[int] = []
    for i in range(len(fac[0])):
        f = fac[0][i]
        exp = int(fac[1][i])
        if exp != 1:
            raise ValueError(f"non-simple factor {f}^{exp}")
        degree = int(pari.poldegree(f))
        if degree != 1:
            raise ValueError(f"nonlinear factor {f}")
        leading = int(pari.polcoef(f, 1))
        constant = int(pari.polcoef(f, 0))
        roots.append((-constant * pow(leading, -1, q)) % q)
    return sorted(roots)


def isogeny_neighbors(roots: list[int], ell: int, q: int) -> dict[int, list[int]]:
    pari = Pari()
    phi = pari.polmodular(ell)
    out: dict[int, list[int]] = {}
    for a in roots:
        row: list[int] = []
        phi_a = pari(f"subst({phi}, x, Mod({a},{q}))")
        for b in roots:
            value = pari(f"subst({phi_a}, y, Mod({b},{q}))")
            if int(value) == 0:
                row.append(b)
        out[a] = sorted(row)
    return out


def walk_cycle(graph: dict[int, list[int]]) -> list[int]:
    start = min(graph)
    if len(graph[start]) != 2:
        raise ValueError("expected a 2-regular cycle")
    prev = None
    current = start
    cycle: list[int] = []
    while True:
        cycle.append(current)
        candidates = [n for n in graph[current] if n != prev]
        if not candidates:
            raise ValueError("cycle walk got stuck")
        nxt = candidates[0]
        if nxt == start:
            break
        prev, current = current, nxt
        if len(cycle) > len(graph):
            raise ValueError("cycle walk did not close")
    if len(cycle) != len(graph):
        # Try the other orientation from the start before giving up.
        prev = None
        current = start
        cycle = []
        first = graph[start][1]
        while True:
            cycle.append(current)
            candidates = [n for n in graph[current] if n != prev]
            nxt = first if current == start else candidates[0]
            if nxt == start:
                break
            prev, current = current, nxt
            if len(cycle) > len(graph):
                raise ValueError("cycle walk did not close")
    if len(cycle) != len(graph):
        raise ValueError(f"expected one cycle of length {len(graph)}, got {len(cycle)}")
    return cycle


def decompose(cycle: list[int], q: int) -> Decomposition:
    cosets: list[list[int]] = []
    coset_sums: list[int] = []
    for r in range(QUOTIENT_SIZE):
        coset = [cycle[(r + k * QUOTIENT_SIZE) % H] for k in range(SUBGROUP_SIZE)]
        cosets.append(coset)
        coset_sums.append(sum(coset) % q)

    V = monic_poly_from_roots(coset_sums, q)
    selected_y = coset_sums[0]
    selected_roots = cosets[0]
    U = monic_poly_from_roots(selected_roots, q)
    return Decomposition(cycle, coset_sums, V, selected_y, U, selected_roots)


def main() -> None:
    pari = Pari()
    pari.allocatemem(256 * 1024 * 1024)
    class_data = pari.quadclassunit(D)
    class_number = int(class_data[0])
    invariants = [int(x) for x in list(class_data[1])]
    hilbert = pari.polclass(D)
    roots = pari_linear_roots(hilbert, Q)
    graph = isogeny_neighbors(roots, ELL, Q)
    degrees = sorted({len(v) for v in graph.values()})
    cycle = walk_cycle(graph)
    dec = decompose(cycle, Q)

    print("embedded decomposed-CM calibration")
    print(f"D={D}")
    print(f"q={Q}")
    print(f"ell_generator_norm={ELL}")
    print(f"class_number={class_number}")
    print(f"class_group_invariants={invariants}")
    print(f"hilbert_degree={int(pari.poldegree(hilbert))}")
    print(f"split_roots={len(roots)}")
    print(f"isogeny_graph_degrees={degrees}")
    print(f"cycle_length={len(cycle)}")
    print()
    print("decomposition")
    print(f"subgroup_size={SUBGROUP_SIZE}")
    print(f"quotient_size={QUOTIENT_SIZE}")
    print(f"V_degree={len(dec.V) - 1}")
    print(f"U_selected_degree={len(dec.U) - 1}")
    print(f"selected_y={dec.selected_y}")
    print(f"selected_coset_roots={dec.selected_roots}")
    print(f"V_coeffs_ascending_mod_q={dec.V}")
    print(f"U_coeffs_ascending_mod_q={dec.U}")
    print()
    print("interpretation")
    print("  decomposed_root_degrees_smaller_than_hilbert_degree=1")
    print("  construction_used_seed_root_and_all_embedded_j_roots=1")
    print("  abstract_class_group_alone_would_not_produce_V_or_U=1")
    print(
        "conclusion=decomposed_CM_saves_final_root_degree_only_after_an_"
        "embedded_CM_root_set_or_equivalent_invariant_has_been_constructed"
    )


if __name__ == "__main__":
    main()
