#!/usr/bin/env python3
"""Tradeoff audit for p24 subgroups generated by one split prime."""

from __future__ import annotations

import argparse
import math

import sympy as sp

from composite_split_cycle_audit import CLASS_NUMBER, split_prime_logs

P = 10**24 + 7


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--prime-bound", type=int, default=20000)
    ap.add_argument("--show", type=int, default=20)
    args = ap.parse_args()

    sqrt_p = math.isqrt(P)
    rows = split_prime_logs(args.prime_bound)
    candidates = []
    for row in rows:
        order = row.order
        index = row.index
        if order >= sqrt_p:
            continue
        proxy = (row.ell + 1) * order
        candidates.append(
            (
                proxy,
                row.ell,
                order,
                index,
                proxy / sqrt_p,
                order / sqrt_p,
                sp.factorint(order),
                sp.factorint(index),
            )
        )

    print("generated subgroup split tradeoff")
    print(f"p={P}")
    print(f"sqrt_floor={sqrt_p}")
    print(f"class_number={CLASS_NUMBER}")
    print(f"prime_bound={args.prime_bound}")
    print(f"split_rows={len(rows)}")
    print()
    print("best_by_seeded_proxy")
    print("ell K_order quotient proxy proxy_over_sqrt order_over_sqrt factors_order factors_quotient")
    for proxy, ell, order, index, proxy_over, order_over, fac_order, fac_index in sorted(candidates)[: args.show]:
        print(
            f"{ell:6d} {order:15d} {index:8d} {proxy:15d} "
            f"{proxy_over:15.6f} {order_over:15.6e} {fac_order} {fac_index}"
        )
    print()
    print("interpretation")
    print("  generated_K_subgroups_have_small_walk_generators_but_recovery_degree_is_their_order=1")
    print("  ell_677_gives_index_314_and_recovery_211*3107441_below_sqrt=1")
    print("  balanced_index_66254_split_has_better_degrees_but_no_low_norm_K_generator_found=1")
    print("conclusion=reported_generated_subgroup_split_tradeoff")


if __name__ == "__main__":
    main()
