#!/usr/bin/env python3
"""Barrier for higher-order Jacobi/hypergeometric trace identities.

Higher-order multiplicative characters can give closed-form point counts, but
an elliptic curve trace is still generated by a degree-2 Weil number.  Thus an
elliptic Jacobi-sum identity has an imaginary quadratic CM field

    Q(sqrt(t^2 - 4p)).

For a base-field multiplicative character over F_p, the relevant cyclotomic
conductor must divide p-1; for the unitary/F_{p^2} variant it must divide p+1
(or at least p^2-1).  More generally, a small-extension Jacobi-sum shortcut
would require the target quadratic conductor to divide p^f-1 for small f.

The strict p24 target fields fail these tests.  Only tiny genus factors such
as 29 or 7 are visible in p-1; the full target quadratic conductors are not
available from cheap cyclotomic character data.
"""

from __future__ import annotations

import math

import sympy as sp

P24 = 10**24 + 7
TARGETS = (
    (1020608380936, 739589633190799177940983),
    (-78903246840, 998443569409526507503607),
    (-1178414874616, 652834595820939249713143),
)


def first_extension_degree_dividing_conductor(conductor: int, max_f: int) -> int | None:
    value = P24 % conductor
    power = 1
    for f in range(1, max_f + 1):
        power = (power * value) % conductor
        if power == 1:
            return f
    return None


def main() -> None:
    max_f = 64
    pminus = P24 - 1
    pplus = P24 + 1
    print("p24 Jacobi-sum CM-field barrier")
    print(f"p={P24}")
    print(f"p_minus_factor={sp.factorint(pminus)}")
    print(f"p_plus_factor={sp.factorint(pplus)}")
    print(f"small_extension_search_max_f={max_f}")
    print()
    print(
        "trace conductor factor_conductor gcd_conductor_pminus "
        "gcd_conductor_pplus divides_pminus divides_pplus divides_p2minus "
        "first_f_le_64"
    )
    for trace, conductor in TARGETS:
        gcd_minus = math.gcd(conductor, pminus)
        gcd_plus = math.gcd(conductor, pplus)
        first_f = first_extension_degree_dividing_conductor(conductor, max_f)
        print(
            f"{trace:15d} {conductor} {sp.factorint(conductor)} "
            f"{gcd_minus} {gcd_plus} "
            f"{int(pminus % conductor == 0)} {int(pplus % conductor == 0)} "
            f"{int(((P24 * P24 - 1) % conductor) == 0)} "
            f"{first_f if first_f is not None else 'none'}"
        )
    print()
    print("interpretation")
    print("  elliptic_jacobi_sum_trace_field_is_quadratic=1")
    print("  target_quadratic_conductor_available_over_Fp_characters=0")
    print("  target_quadratic_conductor_available_over_unitary_Fp2_characters=0")
    print("  target_quadratic_conductor_available_over_small_extensions<=64=0")
    print(
        "conclusion=higher_order_jacobi_or_hypergeometric_identities_do_not_"
        "supply_a_cheap_strict_p24_trace"
    )


if __name__ == "__main__":
    main()
