#!/usr/bin/env python3
"""Exact p24 period accounting for the twisted trace-frame target.

After adjoining E=F_p(mu_m), one H-packet tensor factor is generated by an
n-th root coordinate theta whose E-Frobenius multiplier is

    a = p^ord_m(p) mod n.

The degree-179 intermediate field C inside B is fixed by Q^179-Frobenius, so
Tr_{B/C} is the sum over the order-31 subgroup generated by a^179.
"""

from __future__ import annotations

import math

import sympy as sp

P = 10**24 + 7
M = 66254
N = 3107441


def orbit(modulus: int, multiplier: int, start: int = 1) -> list[int]:
    out: list[int] = []
    seen: set[int] = set()
    value = start % modulus
    while value not in seen:
        seen.add(value)
        out.append(value)
        value = (value * multiplier) % modulus
    return out


def main() -> None:
    ord_m = int(sp.n_order(P % M, M))
    ord_n = int(sp.n_order(P % N, N))
    factor_count = math.gcd(ord_m, ord_n)
    factor_degree = ord_n // factor_count
    c_degree = 179
    b_over_c_degree = factor_degree // c_degree
    a = pow(P, ord_m, N)
    trace_multiplier = pow(a, c_degree, N)
    quotient_multiplier = a
    trace_orbit = orbit(N, trace_multiplier)
    full_factor_orbit = orbit(N, a)
    quotient_reps = [pow(a, t, N) for t in range(c_degree)]
    coset_union = {
        (rep * h) % N
        for rep in quotient_reps
        for h in trace_orbit
    }

    print("p24 tensor factor trace-period identity accounting")
    print(f"p={P}")
    print(f"m={M}")
    print(f"n={N}")
    print(f"ord_m(p)={ord_m}")
    print(f"ord_n(p)={ord_n}")
    print(f"tensor_factor_count_over_E={factor_count}")
    print(f"tensor_factor_degree_over_E={factor_degree}")
    print(f"E_frobenius_multiplier_a=p^ord_m_mod_n={a}")
    print(f"order_of_a_mod_n={int(sp.n_order(a, N))}")
    print(f"C_degree_over_E={c_degree}")
    print(f"B_degree_over_C={b_over_c_degree}")
    print(f"trace_subgroup_generator_a^179_mod_n={trace_multiplier}")
    print(f"trace_subgroup_order={int(sp.n_order(trace_multiplier, N))}")
    print(f"quotient_orbit_length={c_degree}")
    print(f"trace_cosets_partition_factor_orbit={len(coset_union) == len(full_factor_orbit)}")
    print()
    print("first_trace_subgroup_exponents")
    print("  " + ",".join(str(x) for x in trace_orbit[:12]))
    print()
    print("first_degree_179_quotient_representatives")
    print("  " + ",".join(str(x) for x in quotient_reps[:12]))
    print()
    print("period_identity")
    print("  For R_s(X) in E[X]/factor and theta the selected n-root:")
    print("  T_i(R_s)=Tr_{B/C}(theta^i R_s(theta))")
    print("        =sum_{j=0}^{30} theta^(i*(a^179)^j) R_s(theta^((a^179)^j))")
    print("  Its C/E Frobenius conjugates are indexed by t=0..178:")
    print("  sigma^t T_i=sum_{j=0}^{30} theta^(i*a^t*(a^179)^j)")
    print("                    * R_s(theta^(a^t*(a^179)^j))")
    print()
    print("trace_frame")
    print("  proposed_coordinates=i=0,1,2 and t=0..178")
    print("  coordinate_count_over_E=537")
    print("  selected_axis_rank_target=368")
    print("conclusion=reported_tensor_factor_trace_period_identity")


if __name__ == "__main__":
    main()
